### ISSUE TITLE
Bot compilation issue

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#106]
From user

For our reference, here is the trace of the error: Traceback (most recent call last): File "worker.py", line 100, in executeCompileTask archive.unpack(bot_path) File "/home/worker/Halite/apiserver/worker/archive.py", line 26, in unpack shutil.move(os.path.join(tempPath, filename), os.path.join(folderPath, filename)) File "/usr/lib/python3.5/shutil.py", line 542, in move raise Error("Destination path '%s' already exists" % real_dst) shutil.Error: Destination path '/home/worker/Halite/apiserver/worker/tmpqyohabca/bot/bot' already exists

@lidavidm - do we know what is going on?

**Comment by kmisiunas** [comment]
User experiencing this problem here. The submission contains the following files:

https://gist.github.com/kmisiunas/dc47663fe93bd7368561313c91a5d8d6

**Comment by lidavidm** [comment]
Ah. The backend unzips the archive contents into a subdirectory named `bot/`, then moves all the files from the subdirectory to the parent directory. Because the bot upload contains a `bot/` folder, it's complaining that that folder already exists.

**Comment by lidavidm** [comment]
A quick fix would be to rename that folder. On our end, I am not sure why we have this extra step - might be worth getting rid of it to just save the confusion.

**Comment by kmisiunas** [comment]
@lidavidm, thank you for looking into this. I renamed the folder into `mybot` and the problem disappeared, as you suggested. Thanks!

**Comment by harikmenon** [comment]
@lidavidm - do you want make a change to fix this?

**Comment by lidavidm** [comment]
@harikmenon Yeah, would make things less confusing.

**Comment by Snaar** [comment]
If you are touching that part of system, want to take care of #62 as well? :P

**Comment by lidavidm** [comment]
Sure! I swear there was already code for that there, but it seems not.
