### ISSUE TITLE
More tiers

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#112]
Not enough tiers, lets figure out how to add more.

Summarizing via user stories:

- As a non top level player, I want to be able to see my progress more easily as I submit new bots and play the game. 
-- Suggestion: make multiple levels of tiers within Bronze
-- Suggestion: adjust ranks to the normal distribution

- As a non top level player, my rank is going to go down as the game progresses because other players enter (regardless of whether my bot gets better)
-- Suggestion:  Make it clear which 'boss bots' I've beaten
-- Suggestion: Highlight which other players I've beaten

**Comment by jenheilemann** [comment]
🥔 pleeeeeease

**Comment by julskast** [comment]
@jenheilemann thanks for the feedback! Could you share any thoughts on what you'd want?

**Comment by julskast** [comment]
From Forums:
On the topic of tiers I think breaking each tier into smaller tiers with numbers
Ie silver 2, 1, 3, etc
If you guys split tiers it’ll definitely set apart people and give goals
3% is a bit low
Given 600 people

**Comment by Snaar** [comment]
Yeah, I second adding numerical subtiers to existing metal-based ones. Though I would vote for keeping the top-most tier as single non-split tier.

**Comment by jenheilemann** [comment]
Potato tier, lower than bronze :P Seriously. like, bottom 50% or something. Everybody who uploads the starter bot then does nothing with it, essentially.

**Comment by Hadyn** [comment]
I think ranks based upon the normal distribution would be great. Bronze < 50%, Silver < 80%, Gold < 90%, Platinum < 99%, Diamond >= 99%.

**Comment by harikmenon** [comment]
Some ideas we are playing with. Not complete yet.

55% and below is bronze 5
55-60 is bronze 4
60-65 is bronze 3
65-70 is bronze 2
70-75 is bronze 1
75-80 is silver 5
80-85 is silver 4
85-92 is silver 3
92-97 is silver 2
1.5% is silver 1
1.4% is platinum, gold, and diamond

52% and below 
45% -->
3%--> Silver 1, and top tiers

Apprentice, Journeyman, Master

**Comment by harikmenon** [comment]
Given we are at the end of the competition, closing this out. Will consider for Halite III
