### ISSUE TITLE
Replays broken

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#116]
https://halite.io/play/?game_id=1950896&replay_class=0&replay_name=replay-20171027-162649%2B0000--3190201458-384-256-1509121553 - doesnt open due to a json issue

**Comment by lidavidm** [comment]
The replay decompresses fine locally, but is a >10MiB string. It seems the browser can't handle decompressing this, as the result of decompression is an array of all zeroes (though of the right length). Unfortunately, this then has something to do with emscripten, and I'm not sure how best to debug this…
