### ISSUE TITLE
Bring Windows experience on par with Linux/MacOS

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#12]
Implement newer/nicer error messages for Windows too
 Implement non-blocking write (see d4ac3a1 and its commit message)

**Comment by Snaar** [comment]
Yeah I think it's okay not to do this, because we don't expect to use Windows version of halite in completely automated competition. Users who run this themselves can just kill the halite.exe if they have an issue caused by this.
