### ISSUE TITLE
Filter leaderboard by state

### ISSUE THREAD

**Issue by LEARAX** [HaliteChallenge/Halite-II#127]
I'd like to be able to filter the leaderboard by state.

**Comment by harikmenon** [comment]
While this doable in our rest API, there are a couple of reasons we didnt want to show this up in the leaderboard. The key one being we already have a large number of filters and out current ux flow or table design is not conducive to any new columns. 

If you want to see this in your end, I can send you a rest url that does that for you :), but we are probably not going to be adding this to leaderbaord

**Comment by LEARAX** [comment]
I’d love that url.

**Comment by lidavidm** [comment]
@LEARAX: `curl 'api.halite.io/v1/api/leaderboard?filter=country_subdivision_code,=,US-NY'`
