### ISSUE TITLE
Increase Game Window Size

### ISSUE THREAD

**Issue by willisjtc** [HaliteChallenge/Halite-II#13]
the size of the game screen is pretty tiny, and this is coming from someone who has pretty good vision. It's pretty difficult to see all the moving pieces. Anyway we can make the window bigger and potentially have a full screen option?

**Comment by harikmenon** [comment]
@lidavidm : Wanted to check how feasible this is going to be. Can we just scale the canvas to some x times while keeping aspect ratio?

**Comment by lidavidm** [comment]
Yeah, it's just these constants:
https://github.com/HaliteChallenge/Halite-II/blob/bfe2de4cc99ee0b206eafda2a5275ede15e199a6/libhaliteviz/src/assets.js#L5
It would be simple to have the visualizer accept size parameters and fall back to the constants only when needed. Scaling the visualizer on the fly would be hard, unless you just render at a high resolution then scale the canvas down; that can be done in CSS.

**Comment by harikmenon** [comment]
Okay, thanks makes sense. user feedback that sometimes the game is hard to see, was thinking about building a full screen mode.

**Comment by DollarAkshay** [comment]
What library are you guys using for the canvas ?

**Comment by lidavidm** [comment]
@DollarAkshay We are using PIXI.js.

**Comment by harikmenon** [comment]
Given we are at the end of the competition, closing this out. Will consider for Halite III
