### ISSUE TITLE
Default navigation generates negative thrust sometimes

### ISSUE THREAD

**Issue by Snaar** [HaliteChallenge/Halite-II#134]
Reported in https://forums.halite.io/t/c-noop-generates-death/197/6 as something that affects cpp client. Most likely it affects all the other clients too - cpp navigation code is not unique.

**Comment by Janzert** [comment]
I don't see how the default starter bot could be returning a negative thrust from the navigate call. The navigate call will return a negate thrust if a negative max_thrust is passed in. But the starter bot passes in a static MAX_SPEED / 2.

The only other way to get a negative thrust is by getting a negative distance to target and that requires getting a negative result from a sqrt() call.

**Comment by Snaar** [comment]
Failed to reproduce.
