### ISSUE TITLE
Use Gunicorn instead of Flask built-in server

### ISSUE THREAD

**Issue by lidavidm** [HaliteChallenge/Halite-II#147]
The built-in Flask server is single-threaded, with Gunicorn or something similar, we can serve multiple requests at the same time, hopefully speeding up the API and coordinator (up to a limit). I tried swapping two of the coordinators to Gunicorn with workers=5, bringing up our games/hour from 700 to 930.

**Comment by j-clap** [comment]
Why not use multithread in Flask instead? I get that the Flask documentation says that it's for dev mode only, but I've personally had pretty positive experiences with it (one exception is that it's not the best at freeing sockets; only seen that happening once though and that was via a massive quasi-DDoS which would've brought the machine down either way)

**Comment by lidavidm** [comment]
Ah that's fair. I can try that as well.
