### ISSUE TITLE
Starter kits don't let bots take advantage of initial 60s map timeout

### ISSUE THREAD

**Issue by Snaar** [HaliteChallenge/Halite-II#151]
Issue is that most (all?) kits send bot name to halite right away, but that's what stops the initial 60s timeout, so right now there is no way to take advantage of the initial 60s timeout for preprocessing the map. Kits need to cache the bot name and delay sending it until getting the map for first turn. Fixed in:

- [x] C++
- [ ] CSharp
- [x] Clojure
- [x] Dart
- [x] Elixir
- [ ] Go
- [x] Haskell
- [x] Java
- [x] JavaScript
- [x] Julia
- [ ] Kotlin
- [x] OCaml
- [ ] PHP
- [x] Python3 & ML-StarterBot-Python
- [x] Ruby
- [x] Rust
- [ ] Scala
- [x] Swift

**Comment by Snaar** [comment]
We got Python and cpp kits fixed. I'll be going through rest one by one over next few days.

**Comment by hypirion** [comment]
The Clojure kit is able to take advantage of the initial timeout if you want it to: `(initialize-game ...)` reads the player + map info, but the bot doesn't send back its name before [`(io/send-done-initialized)`](https://github.com/HaliteChallenge/Halite-II/blob/afe9836e2efa8f377c7ed69d2900682e26a15c7f/airesources/Clojure/src/MyBot.clj#L52) is called.

**Comment by Snaar** [comment]
@hypirion do you mind adding example of initial map analysis so it's clear where to do it in the kit? For example for cpp I've done: https://github.com/HaliteChallenge/Halite-II/commit/76cb289920d053c96d1f12997a878a57bc367ca0#diff-eef5a713e6a41b5875a4f93bcbe7093aR10

**Comment by hypirion** [comment]
@Snaar: Yeah, no problem. I'll see if I can come up with an example.

**Comment by mw0401** [comment]
I still don't understand what "fixed" means. In Python how do access the map information before I submit a bot name?

I can't seem to access game that before I send the command to start my first turn.

this works:
game = hlt.Game("Bot")
Q = game.initial_map

this doesn't:
Q = hlt.Game.initial_map
game = hlt.Game("Bot")

Am I coding it wrong or is it not available, or available differently?

**Comment by harikmenon** [comment]
Closing this out since this is the end of the competition
