### ISSUE TITLE
Go bots still error out on Slice methods (some games)

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#154]
Did we update the GPU workers as well?

"Error": {
   "Message": "ERRORED! Got Exception (if any): ERROR: Bot #0: Received invalid character 'src/hlt/gamemap.go:121: undefined: sort.Slices'. (at character 1.)\nInput received from bot:\nsrc/hlt/gamemap.go:121: undefined: sort.Slice\n^; Response received (if any): src/hlt/gamemap.go:121: undefined: sort.Slicesrc/hlt/gamemap.go:143: undefined: sort.Slicesrc/hlt/gamemap.go:158: undefined: sort.Slicesrc/hlt/gamemap.go:173: undefined: sort.Slicesrc/hlt/gamemap.go:189: undefined:  ... (and many more)

**Comment by lidavidm** [comment]
Thought I did. Looking into it.

**Comment by lidavidm** [comment]
Forgot to uninstall Go 1.7, which shadowed 1.9. The new GPU worker image has been built.

**Comment by harikmenon** [comment]
Thanks David, marking this as completed
