### ISSUE TITLE
Pumpkins for planets

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#160]
Download the sprite sheet here: https://drive.google.com/file/d/0B0Fz2uOQ6YoOYm5TSFRhcHBvajA/view?usp=sharing

Pumpkin design:

Clear image here:
![pumpkin_planet 1](https://user-images.githubusercontent.com/764613/32193802-c8ebd8ec-bd8e-11e7-800f-511d245e5c82.png)

--

**Comment by lidavidm** [comment]
https://github.com/HaliteChallenge/Halite-II/pull/163

**Comment by harikmenon** [comment]
This is completed, Thanks @lidavidm
