### ISSUE TITLE
Leagues list page

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#161]
See here: https://www.screencast.com/t/kYj0nyIBU7

Similar to Hackathon list page.

Requirements:
- [ ] Link to page from top navigation
- [ ] Title of page is "Halite Leagues"
- [ ] User sees two filters: filter by league name and filter by category. Should be multi-select filters using same UI as leaderboard filters, with way to 'clear all'
- [ ] List should have three columns: League Name, Description, and Category
- [ ] League name should link to individual League Page. See other github ticket: https://github.com/HaliteChallenge/Halite-II/issues/162

API - http://api.halite.io/v1/api/leagues

**Comment by toannguyen132** [comment]
when I send a request for getting leagues list I get only 4 data type of a league item: id, name, category, query. There is no description returned by the server. 

@julskast 

<img width="419" alt="screenshot 2017-10-31 23 26 07" src="https://user-images.githubusercontent.com/7789414/32262637-ea1a8d42-be92-11e7-899f-b28d10d99960.png">

**Comment by toannguyen132** [comment]
@harikmenon does the API support filter? How can I filter the leagues?
I tried the query `name,=,Top%2020%20Javascript%20Bots` (like the leaderboard) but it didn't work.

**Comment by harikmenon** [comment]
Filter in front end.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
