### ISSUE TITLE
Single league page

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#162]
See mockup below

Requirements:
- [ ] Breadcrumbs are leagues--> current page
- [ ] Page title is name of hackathon
- [ ] Description goes below
- [ ] Include category as link to all leagues from that category (goes back to leagues browse page but filtered)
- [ ] Big button should be share (though ideally would be a little smaller size!) and should have the same UX as the share from the visualizer pages but should share current page of course
- [ ] Table should be the same as the hackathon except should say "League rank" and should include "level" e.g. professional.
- [ ] Can we also include overall rank? [Hari - we should make this a tooltip or something, I dont want the focus to go away from league rank]

![image](https://user-images.githubusercontent.com/764613/32194947-38961074-bd92-11e7-84ff-cd2fe34f0ef4.png)

**Comment by toannguyen132** [comment]
@harikmenon what is the API url to get an individual league?

**Comment by harikmenon** [comment]
There is no url, just a single leagues api. You need to take the query and use it the same way you do in the leaderbord

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by toannguyen132** [comment]
@harikmenon so I need to send a request to /leaderboard and filter by the league id?
What is the filter name for league id? I found this filters type in the API code.
<img width="716" alt="screenshot 2017-11-01 11 17 37" src="https://user-images.githubusercontent.com/7789414/32290124-4a621ba8-bef6-11e7-81a9-a5d9328f955c.png">

**Comment by harikmenon** [comment]
No not by league id, you should use the query field in the api and translate that to the leaderboard API
