### ISSUE TITLE
Pre-game is serial and not parallel

### ISSUE THREAD

**Issue by Snaar** [HaliteChallenge/Halite-II#165]
Discovered while working on #151. It looks like halite will initialize bots one at a time, so if you have 4 bots each taking the full 1 minute they are allowed to take, then the pre-game period will take 4 minutes.

**Comment by Janzert** [comment]
I don't see this locally using Ubuntu/gcc to build the environment. But this behavior would be allowed from the std::async call used. It is allowed to use either a launch policy of std::launch::async (threads) or std::launch::deferred (just run it when the result is called for). I'd be a bit surprised if it's using a different policy for the initialization than for the rest of the moves, but still possible and allowed by the call.

If this is what is happening and your system is using the deferred launch policy you should be seeing the "Init Message sent to player <n>" message not appear until the previous bot finishes its initialization time. What OS/compiler is your halite environment built under?

**Comment by Snaar** [comment]
Yeah, the init message appeared serially with delay as you described. It's ubuntu 16.04 with gcc 5.4.0. I imagine it was the same for normal turns as well, just not visible while running sample bots.
