### ISSUE TITLE
Install Pytorch in the GPU images

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#169]

**Comment by Janzert** [comment]
It will work on cpu only machines as well. Maybe to slowly to be of much use though? It would be nice to keep the packages as similar as possible.

**Comment by harikmenon** [comment]
Agreed, I dont mind it on both. We generally separate images here, whatever @lidavidm thinks its best here.

**Comment by lidavidm** [comment]
@harikmenon This should be done right? I'm going to close it.
