### ISSUE TITLE
Improve python starter kit IO

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#173]
I am looking at networking.py in the Python starter kit and see some inefficiencies with the I/O.

The _send_string method flushes I/O at the end as well as _done_sending. However, the only two uses of these functions are inside _send_command_queue, which repeatedly calls _send_string before calling _done_sending. Removing the flush call inside _send_string and only flushing I/O in _done_sending would not affect anything and would greatly improve I/O efficiency.

https://forums.halite.io/t/speeding-up-python-bots/306/13

**Comment by j-clap** [comment]
Fixed, but this should not account for a significant slowdown. Most of the slowdown in python is due to the fact python is python and std(out|err) writes are slow. My guess is at most this will bring a 2-5% speed-up, which is insignificant in the scheme of things.
