### ISSUE TITLE
Combat oddities + Damage reporting

### ISSUE THREAD

**Issue by shummie** [HaliteChallenge/Halite-II#189]
Sorry, this is going to be long and confusing. Please see the attached replay for reference.

This is a multi-part issue which may all be related. The first part:

Inconsistency in damage reporting.
Here is the output in the console for the attached game:

> Opening a file at .\replay-20171101-231425-0500--960310599-312-208-459563.hlt
> Player #0, Cure-9, came in rank #2 and was last alive on frame #13, producing 0 ships and dealing 896 damage!
> Player #1, Cure-8, came in rank #1 and was last alive on frame #13, producing 0 ships and dealing 960 damage!
> Player 0 is dead
> Player 1 is dead

Everything looks fine. Cure-8 dealt more damage than Cure-9 and is the winner.
Now, watch the replay and scroll to the end of the game. 

If you expand the player details box, it says Cure-9 dealt 896 damage while Cure-8 dealt 832.
Weirdly, the winner of the game is Cure-8.

Ok, now, even more weird. Scroll down to the post game dashboard.
You can see that according to the graph, Cure-9 dealt more damage over the entire game. Ok, fine, but then look at the health, Cure-8 always has more health, this is counter-intuitive to the damage graph. This could be attributed to overkill damage being recorded weirdly?

So, how is overkill damage / collision damage treated?
With 3 starting ships at 255 health each, there should only be 765 health available. If a ship absorbs overkill damage, does all of the damage get counted as damage? That is:

Player B has 63 health left, and is in range of 3 of Player A's ships. They would normally take 64 * 3 = 192 damage. Does this get recorded as 192 damage dealt in favor of player A? Or would they only get credit for 63 damage. I think the latter is the best way to treat damage dealt because Player B should not be penalized for making a smart tactical move by absorbing player's A overkill damage. 

Also, what if Player B with 63 health crashes into Player A's ship with 255 health. Does Player B get credited for 255 damage dealt and Player A get 63 damage dealt?

Ok, the above was all related to damage reporting. Now for weird combat oddities in the same game... Refer to frame 7, just before any damage is dealt. 

Advance 1 frame. Player details shows 192 damage dealt but no ships take damage advance 1 more frame and then you see that ship 4 and ship 2 take 192 damage. (Also, zooming is needed. Targeting ship 3 is nearly impossible. I'm using fohristiwhirl's viewer to see this more clearly.

It looks like there's a delay in how the replay viewer is showing the damage. Ok, now, I will put this disclaimer that I'm using the viewer that fohristiwhirl has created so if there's a discrepancy it could be because of the viewer, but it's impossible to decipher in the web replay viewer. Not only that it seems like there's an issue with the display as it as evidenced by everything above.

POST EDIT: (Ok, turn 8 might be turn 9 and turn 9 might be turn 10, there's a discrepency in the viewer, I hope you can follow along and understand what i'm trying to say.)
After turn 8, when the lead ships have taken damage, it looks like (I don't really want to calculate every single ship distance, but I can if needed) that all three ships are in range of each other. My understanding of the rules indicates that because of this, every ship then spreads its damage with every enemy ship (or, each ship spreads its damage to every enemy ship in range.) Now the weirdness starts.

Turn 8: 
Player / Ship ID / Health:
Cure-8 / 0 / 255
Cure-8 / 1 / 255
Cure-8 / 2 / 63
Cure-9 / 3 / 255
Cure-9 / 4 / 63
Cure-9 / 5 / 255

Turn 9:
Player / Ship ID / Health:
Cure-8 / 0 / 234
Cure-8 / 1 / 106
Cure-8 / 2 / 42
Cure-9 / 3 / 255
Cure-9 / 4 / DEAD
Cure-9 / 5 / 255

What??? That makes no sense to me. Ok, fine, I'll calculate the distance between each ship.
Turn 8: 
Player / Ship ID / Health / x / y:
Cure-8 / 0 / 255 / 157.813137 / 102.910845
Cure-8 / 1 / 255 / 156.323852 / 101.247936
Cure-8 / 2 / 63 / 155.766997 / 102.140227
Cure-9 / 3 / 255 / 157.608791 / 105.870693
Cure-9 / 4 / 63 / 156.702169 / 104.882704
Cure-9 / 5 / 255 / 155.999424 / 105.676089

Distance between 1 and 3 looks to be the furthest (eyeballing it) at 4.79 center to center. I think weapon ranges are from edge to edge? So all ships should be in range. So, why does ship 4 take ALL of Cure-8's damage, while all of Cure-8's ships get damaged, and not even evenly? My expectation is that EVERY ship would take 64 damage since every ship is in range of every other ship. Or.. actually, each ship would take 21.33333 damage. Is health stored as an int or as a floating point as well? How does the damage get split? does each ship take 21 damage, 22 damage, or 21.333 and health gets rounded later?

Ok, sorry, this is a lot, probably worth splitting into multiple issues, but I think they're all inter-related.
[replay-20171101-231425-0500--960310599-312-208-459563.zip](https://github.com/HaliteChallenge/Halite-II/files/1436513/replay-20171101-231425-0500--960310599-312-208-459563.zip)

**Comment by Janzert** [comment]
Regarding the edit addition, I think you might be using a halite environment that doesn't include the fix for #110 damage calcution against multiple targets. It may be causing at least some of the other wierdness you saw as well.

**Comment by shummie** [comment]
That might be part of the cause, but here's a game from the server that definitely has the replay damage/viewer issues, plus the damage tiebreaker issue. 

https://halite.io/play/?game_id=2109630&replay_class=1&replay_name=replay-20171101-155201%2B0000--3659375511-288-192-1509551519

I haven't dug into it to see if the same damage issue occurs or not though.

**Comment by lidavidm** [comment]
https://github.com/HaliteChallenge/Halite-II/pull/191 might also be related. Will dig into the replays once I find some time.

**Comment by shummie** [comment]
[replay-20171102-220456-0500--206490617-240-160-541797.zip](https://github.com/HaliteChallenge/Halite-II/files/1439988/replay-20171102-220456-0500--206490617-240-160-541797.zip)

This is a replay from the latest binary (as if November 2nd). Still weirdness with combat and multiple ships. If you look at turn 13? All 6 ships are easily within range of every other one. Of particular note, Ship 1 and Ship 4 are both at 63 health. But, one frame later, for some reason, Cure 8's ship 4 escapes completely unscathed when it starts its turn in range of all of Cure-11's ships, while ship 1 gets destroyed. 

Still weird is Ship 2 takes no damage while Ship 0 takes 128. So, it looks like 3 ships worth of attack is done, but in an inconsistent manner. Meanwhile, Ship 5 takes 64 damage while Ship 3 takes 128. So the total amount of damage dealt is consistent, but the damage does not look like it's being spread out.

It's a little frustrating trying to deal and debug this since there's still the attack range bug that hasn't yet been merged in. These combat changes and discrepancies is making it difficult to want to try to improve my bot when these issues still exist.

**Comment by fohristiwhirl** [comment]
Could the issues in #199 explain this replay?

**Comment by shummie** [comment]
Maybe? I'll see if I can replicate once the ship weapon radius + collision time changes are incorporated into the latest binary.

**Comment by Janzert** [comment]
@fohristiwhirl actually yes it will, I hadn't even considered that aspect of it.

**Comment by shummie** [comment]
Looks like #191 and #199 fixed this issue. Thanks everyone!
