### ISSUE TITLE
C++ Issues

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#19]
1) C++ Issues
1a) The halite binary is compiled dynamically. I had a slightly older version of libstdc++6 on my machine, which was incompatible and somewhat annoying to update. If you just compile statically, this won't be a problem for people.
1b) The starter C++ halite bot dies immediately -- seems like it's not publishing commands at all. I didn't debug further.

**Comment by julskast** [comment]
https://forums.halite.io/t/bug-reports-and-sharp-edges/105/3

**Comment by markstev** [comment]
Regarding 1a, this was on linux (ubuntu) using a droplet instance I created about a year ago. Maybe I should just keep my machine more up to date, but a year isn't *that* old. I am not a compiler expert, but my understanding is that just adding the flag "-static" to the compile options should make the compiled binary less susceptible to environment differences between where you compiled and where users run it, with the downside of making the binary larger and slower to compile (though I doubt those are significant issues in the context of halite).

**Comment by Snaar** [comment]
1a was fixed already some time ago, can you double-check? 1b is in progress - I expect to release it in about a day or two.

**Comment by Snaar** [comment]
If you want, you can try cpp-client branch in Snaar/Halite-II - the communication with server is good now, but everything else is ugly.

**Comment by markstev** [comment]
Thanks! I'm on my way to work now, but I'll try it tonight.

**Comment by Snaar** [comment]
Actually, if you got the binary from website just now recently, maybe it's a sign website has old build. @harikmenon can you check if website pack has recent halite build?

**Comment by harikmenon** [comment]
I built it at 6:00 pm last night, any changes after that?

**Comment by Snaar** [comment]
Ok I've just checked both https://halite.io/assets/downloads/Halite2_Linux-x64.zip and https://halite.io/assets/downloads/Halite2_C++_Linux-x64.zip and they both have statically linked halite:

```
$ ldd halite 
	not a dynamic executable
```

What does ldd say on your machine?

**Comment by Snaar** [comment]
C++ client in github should be good for linux/gcc now. I know that MSVC is broken right now for sure, I'll look at it later. Not sure about clang.

**Comment by Snaar** [comment]
Fixed MSVC.

**Comment by harikmenon** [comment]
@Snaar , do you want me to build and deploy executables for all platforms?

**Comment by Snaar** [comment]
Oh, to be clear, this is cpp client, not halite, so we don't need to pre-build anything, just update the cpp starter kit, right?

**Comment by harikmenon** [comment]
Oh okay my bad. Looks good. Closing this now

**Comment by Snaar** [comment]
@markstev feel free to reopen if you have more data about static linking not actually being static
