### ISSUE TITLE
Date format backwards for Americans

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#197]
Should be  11/1/17 and 10/31/17 - mm/dd/yy is the correct format for the US which is where we are and where over 60% of players are from.

![image](https://user-images.githubusercontent.com/764613/32339041-e9de67a0-bfcc-11e7-9754-452cf3763ce1.png)

**Comment by Janzert** [comment]
I've never understood why not use a format like yyyy/mm/dd, that way everyone can be mad. But at least it will sort lexicographically in the correct order. ;)

**Comment by julskast** [comment]
Oh, glad to see we're moving back to 'x days ago' which avoids this issue completely! I'll close this ticket.
