### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by petroseskinder** [HaliteChallenge/Halite-II#2]
The website is down. Also when is the launch of second season?

<img width="1073" alt="screen shot 2017-09-13 at 12 44 56 am" src="https://user-images.githubusercontent.com/5799696/30360022-e98d160c-981c-11e7-846e-272bbe2890e2.png">

**Comment by Janzert** [comment]
http://halite.io seems to be fine. Just https is broken and I believe they mentioned on discord that they would be fixing it tomorrow.
