### ISSUE TITLE
ML bot timesout

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#217]
https://forums.halite.io/t/bot-times-out-before-the-game-starts/458

**Comment by lidavidm** [comment]
When I test initializing the bot, it terminates with exit code 137 about 1 in 10 times, indicating the process is getting a SIGKILL. But I can't tell why; cgexec even in debug logging doesn't tell me anything useful, and dmesg doesn't show kills due to memory.

**Comment by xerus** [comment]
Can it be gpu memory? tensorflow can be greedy. I'll turn off GPU usage and see whether it changes anything.

**Comment by lidavidm** [comment]
Possibly, but each user should have their own GPU, so they shouldn't be conflicting with each other.

**Comment by harikmenon** [comment]
@piotrzielinski also mentioned this.

**Comment by lidavidm** [comment]
I'm going to stand up a worker and just loop the bot/loading the tensorflow model for a while, see if I can reproduce it. Peeking into the database, it does seem like this started happening on 11/3 for both xerus and piotr.

**Comment by lidavidm** [comment]
Well, here's a bigger problem. Unless I'm mistaken, GPU workers don't seem to actually have GPU access right now.

**Comment by lidavidm** [comment]
And somewhat coincidentally, the last time a GPU image was created was November 3rd. Might have accidentally broken something then, currently building a new image.

**Comment by lidavidm** [comment]
@harikmenon I recreated the GPU worker image. Something happened while installing PyTorch I guess, causing us to lose GPU access.

**Comment by harikmenon** [comment]
Okay sweet. Thanks! Closing this issue for now.
