### ISSUE TITLE
Update docs with ships docked per planet

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#22]
The docs1 indicate that "The maximum number of ships that can be docked to a planet is equal to the radius. E.g. a planet with a radius of 3 units may have up to 3 ships docked to it at once." But, the max actually is a property of the Planet and seems unrelated to the radius.

**Comment by julskast** [comment]
https://forums.halite.io/t/bug-reports-and-sharp-edges/105/3

**Comment by harikmenon** [comment]
This is fixed
