### ISSUE TITLE
C# query not working for leagues

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#224]
https://halite.io/league-board?id=25&leaguename=Top%2025%20C#&language=C#/.NET%20Core,C#/Mono&limit=25

not returning results

**Comment by lidavidm** [comment]
There needs to be separate filter clauses for C#/.NET Core and C#/Mono; putting them into a single clause results in a 500 for some reason. Correct query: https://api.halite.io/v1/api/leaderboard?offset=0&limit=25&filter=language%2C%3D%2CC%23%2F.NET%20Core&filter=language%2C%3D%2CC%23%2FMono
