### ISSUE TITLE
Create new language kit guidelines

### ISSUE THREAD

**Issue by Snaar** [HaliteChallenge/Halite-II#226]
Writing down my thoughts here for now.

Basic kit:
- default bot name different from default names of other languages
- has logging that creates/overwrites log file with ${id}-${name}.log as file name
- reads in the map and all the entities on it
- makes it obvious how to take advantage of pre-game 60s timeout (#151)
- utility to convert radians into clipped integer degrees as expected by the halite engine - example https://github.com/HaliteChallenge/Halite-II/blob/master/airesources/Java/hlt/Util.java
- the magnitude component of thrust command should be rounded down to prevent ship from crashing into things

Full kit:
- all of the functions on website documentation available

**Comment by mikemeier** [comment]
@Snaar done

**Comment by harikmenon** [comment]
Closing this out since this is the end of the competition
