### ISSUE TITLE
Is ML league supposed to be empty?

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#227]
I thought we had ML players but this is empty:
https://halite.io/league-board?id=3&leaguename=Top%2025%20Machine%20Learning&language=Machine%2520Learning,ML&limit=25

**Comment by harikmenon** [comment]
Basically missing 2 folks

**Comment by julskast** [comment]
I'm cool with that @harikmenon  - that's their own user error essentially. Thanks for fixing!
