### ISSUE TITLE
low frequency errors on GPU workers

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#23]
@lidavidm any idea whats going on?

ERROR:root:Error on get task Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "worker.py", line 315, in main
    executeGameTask(int(task["width"]), int(task["height"]), task["users"], backend)
  File "worker.py", line 252, in executeGameTask
    users, parsed_output = parseGameOutput(raw_output, users)
  File "worker.py", line 229, in parseGameOutput
    result = json.loads(output)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lidavidm** [comment]
The game environment is crashing, I'll look at this when I get a chance

**Comment by lidavidm** [comment]
I can see the issue in the logs, but it's not enough to reproduce; currently capturing more detailed logs

**Comment by lidavidm** [comment]
Ah, it has to do with bots that don't initialize properly in quiet mode. Normally, the environment dumps the bot output to the screen, but in quiet mode, it looks like we're not catching the right exception, and so halite crashes instead. I will work on reproducing this locally.

**Comment by lidavidm** [comment]
`handle_frame_networking` is throwing an exception, which isn't caught, so when we get the value from the future, the exception is rethrown and this…aborts the process? Will continue debugging with the core dump later

**Comment by lidavidm** [comment]
I GOT IT. PR incoming.
