### ISSUE TITLE
environment: halite generated two identical log file

### ISSUE THREAD

**Issue by wizzup** [HaliteChallenge/Halite-II#230]
running `halite './mybot' './mybot'` create two identical json log files `0-number.log` and `1-number.log`
    
    $ diff 0-1510040891.log 1-1510040891.log
    
The `number` in log filename is change every run.

**Comment by Snaar** [comment]
What part is unexpected for you here?

**Comment by Snaar** [comment]
I.e. this is normal behaviour - those logs are generated by engine when bots crash. "0" and "1" are bot IDs, the "number" is the timestamp.

**Comment by wizzup** [comment]
I just don't understand ,what is the purpose of having two identical files? Why don't just create single `game_log.json`?

Forgive me if there is requirement to have two files elsewhere in the system.

**Comment by harikmenon** [comment]
@wizzup the reason is because they are 2 different bots and in the server we need to provide the logs when there is a timeout or error to the player
