### ISSUE TITLE
Challenge a friend: Join & Play

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#233]
1.5 Join - New players only
- New player gets email invite
- New player visits the site and sees instructions (create a new learn page?)
- New player makes an account (what if different email?) - does challenger get notified?
- New user goes through onboarding & submits a bot - does challenger get notified?
- Does new user get to say when they're ready to accept the challenge? E.g. if you challenge me, chances are you've been playing already. I'd like to get my bot good before I accept your challenge.

2. Play
- Does challengee need to accept a challenge? What happens for top players - will they get challenged too often? Or does challengee even get notified? Maybe players can turn off challenge notifications separately via sendgrid as a new unsub group.
- Challenger plays challenged (backend)
- Challenger & challenged learn they've played (notification? Emails?)

Sample copy:
"Hi Julskast, we're letting you know that you've started playing Harikmenon as part of a player-to-player challenge. To see the results of the challenge you can go to the "analyze" section of your user profile to see stats, or watch a video of the two of you"

**Comment by Janzert** [comment]
Just a note, these games should not cause rating updates. Allowing rated games with self selected opponents is an invitation for rating manipulation.
