### ISSUE TITLE
mobile conversion improvements

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#236]
**Recommendations**
- Change the 'get started' button on the homepage to a 'sign up' CTA on mobile only AND/OR
- Collapse learn page menus on mobile so there's not so long of a scroll 

**Research:**
Current flow is:
- Users arrive on homepage and click one of three buttons:
-- Sign in
-- Hamburger
-- Get Started
![image](https://user-images.githubusercontent.com/764613/32510797-b97bf266-c3bf-11e7-99d7-0602de774a71.png)

Unclear where Hamburger journey takes the user, but chances are they'll end up on the Learn homepage. But on mobile, that page isn't great. Most users never make it past the main menu at the top:
![image](https://user-images.githubusercontent.com/764613/32510850-f2807992-c3bf-11e7-879e-6abbd9753bc4.png)
They never see the 'how to get started' content.

**Comment by toannguyen132** [comment]
@julskast do you want me to move the menu below the content? if I make the menu collapse, it cannot be expanded because there is no trigger that can expand the menu.

`Change the 'get started' button on the homepage to a 'sign up' CTA on mobile only AND/OR`
What is the URL of the 'sign up' button? this button appears on mobile only, doesn't it?

**Comment by julskast** [comment]
@toannguyen132 - let's only do the button for now, not the menu.

Sign up button should go to ${api.LOGIN_SERVER_URL}/github - same as the button in the nav when user's not logged in. And it should replace the 'get started' button only on mobile and only when user is not logged in.

**Comment by harikmenon** [comment]
@toannguyen132 lets do this one: Change the 'get started' button on the homepage to a 'sign up' CTA on mobile only AND/OR
