### ISSUE TITLE
Seeds don't produce the same results across different platforms

### ISSUE THREAD

**Issue by Janzert** [HaliteChallenge/Halite-II#241]
After a bit of investigation it seems this is because standard library distributions are not required to give the same results across platforms. The generator itself apparantly is consistent. See the stackoverflow questions [here](https://stackoverflow.com/questions/26538627/c11-cross-compiler-standard-library-random-distribution-reproducibility) and [here](https://stackoverflow.com/questions/34903356/c11-random-number-distributions-are-not-consistent-across-platforms-what-al).

It looks like we use uniform int and real distributions and probably most reasonable approach is to add our own implentations to use everywhere.

**Comment by lidavidm** [comment]
Looks like the only non-libstdcxx implementation I can find (after a bit of searching) is Boost, and we'd probably rather not pull in all of that. (Well, the second SO link has an implementation, but no comment on how it really works.) I'll look into implementing these then. Either that, or pulling [Clang's implementation](https://github.com/llvm-mirror/libcxx/blob/master/include/random) which is MIT-licensed.
