### ISSUE TITLE
Challenge player support

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#247]
How difficult would it be for us to write an api to challenge a player.

E.g 

1.  I can select 1 or 3 other plays and challenge them
2. We run about 30 games (max 3 challenges/day) across a combination of maps and player count
3. These matches will not affect rating in any way
4. user can see the status of the challenge (not started, started, completed)

Also:
- [x] Mu/sigma/rank to game_participant?
- [x] Field to track whether game is ranked

**Comment by lidavidm** [comment]
We would need a table to store the challenges, some fields on the player table to keep track of the most recent challenge/number of challenges/day, some changes in the matchmaking code to actually issue the challenge, and changes in the worker & coordinator to keep track of the fact that we are not updating rating.

**Comment by harikmenon** [comment]
Makes sense.

An alternate thing would be to have as user_challenge table that stores user to challenge id and date of creation and status, Challenges table with challenge id and participants id and updates to the game table to have a challenge id.

Would that work better, how much time would you estimate would it take to wire this up. We are seeing a lot of feedback on this front and we wanted to see if we can build this feature to enhance our growth rate.

**Comment by lidavidm** [comment]
Yeah, that sounds good. I'll take a look tonight after I test my fix for #241

**Comment by lidavidm** [comment]
@harikmenon Are challenges publicly visible, or only to the involved players? When matchmaking, we issue special games involving only the affected players, right?

**Comment by harikmenon** [comment]
Publicity visible and yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lidavidm** [comment]
One more thing - @harikmenon how should we handle ties? (Each bot gets points based on their rank in the game; highest points wins, but there can be ties). Also, if they challenge 3 people, but 2-player games are played, there might be an unequal number of games between the participants.

**Comment by harikmenon** [comment]
cant we use our tiebraker logic for this? I think its fine, its a best faith effort on our side to run 30 games with as many variations as we can

**Comment by lidavidm** [comment]
So the issue is breaking ties after they've played the 30 games, I guess we can parse the replays and aggregate that information then.
