### ISSUE TITLE
Browser issue - chrome, MacOS

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#25]
Hello. Whenever I am trying to access the halite.io website from Google Chrome nearly all of the pages are blank, and I cannot sign in. The two exceptions to this are the Learn page and the Download page. Not sure if this matters, but I am on macOS. Thanks in advance for the help. :slight_smile:
https://forums.halite.io/t/blank-pages-on-website/123/4

**Comment by scarpent** [comment]
Hard refresh took care of this for me (Chrome, macOS), and sounds like for kwindischman, too.
