### ISSUE TITLE
Add a button to download replay

### ISSUE THREAD

**Issue by shummie** [HaliteChallenge/Halite-II#250]
It would be nice to have a button to download a specific replay from the server instead of having to manipulate a URL to download the replay.

**Comment by lidavidm** [comment]
Ah, I've been meaning to do this. This + the full screen mode would help, along with searching for nearest ship on click.

**Comment by harikmenon** [comment]
@shummie there is a couple of places we can add this. 
a)Game Videos in the user profile page
b) in the Visualizer itself next to the playback buttons

What feels more natural and easiest to access for you?

**Comment by bovard** [comment]
@harikmenon can you do both?

**Comment by shummie** [comment]
I see pros for both. I would personally prefer to download an interesting replay, and I would know if it's interesting after I've viewed it, so a button next to the Share button that currently exists would be good. I don't see many situations where I would want to d/l a replay without having viewed it first, but having it on the profile page would make it easier to download multiple replays at once.

**Comment by harikmenon** [comment]
@toannguyen132 can you add a download button next to the next frame button in the playback controls in the visualizer? Styling is the same as the other button on the list. This button should only be visible when you are playing a game from the server and not when you have uploaded a replay. Also, you should be able to get the link to the replay file in the api on the page and enable users to click on it to download the file
