### ISSUE TITLE
API does not auto associate organizations correctly

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#254]
I think I found a interesting case. If you you mark yourself as a professional and add E.g columbia.edu as your work email, we fail to associate it.

I'm manually fixing this up now. @lidavidm if this is a super low risk fix, lets fix it otherwise lets leave that code path alone.

**Comment by lidavidm** [comment]
Hmm. The verification code doesn't check your level at all (except for high school), so I'm not sure what's going on. I was able to set myself as a Cornell professional just now.

**Comment by harikmenon** [comment]
Hmm, then is something else. Dont worry about it then. 'm associating these manually and the influx is not hard to manage
