### ISSUE TITLE
Can the engine send more decimal places?

### ISSUE THREAD

**Issue by fohristiwhirl** [HaliteChallenge/Halite-II#258]
The engine currently sends 4 decimal places for coordinates. I wonder if this could be, say, 6? As it stands, real games have collisions because ships weren't quite where they thought they were...

(I likely would have lost anyway, but my ships [didn't believe](https://play.golang.org/p/oV4loODTGV) they would [crash into each other](https://halite.io/play/?game_id=2445100&replay_class=1&replay_name=replay-20171109-031212%2B0000--711522276-240-160-1510197111) here.)

Each extra decimal place should reduce the chances of this sort of thing by 90% I suppose.

**Comment by DanielVF** [comment]
Note that these engine to game messages are not traveling over the net, or being saved in replays. We wouldn't be bloating the size of everything to increase them.

**Comment by fohristiwhirl** [comment]
Well, actually the replays already have more precision than this.

**Comment by fohristiwhirl** [comment]
PR at #263
