### ISSUE TITLE
Submission size limit

### ISSUE THREAD

**Issue by TotalVerb** [HaliteChallenge/Halite-II#259]
There seems to be a 20MB size limit for submissions, which makes it difficult to bundle dependencies. Could this be raised to something closer to what the actual size limit is for the compiled bot on disk?

**Comment by lidavidm** [comment]
@harikmenon Change the following in `config.py`:

```
MAX_BOT_UPLOAD_SIZE = 20 * 1024 * 1024
```

to something like

```
MAX_BOT_UPLOAD_SIZE = 100 * 1024 * 1024
```

**Comment by harikmenon** [comment]
Made the change will deploy tomorrow
