### ISSUE TITLE
Seeds are not reproducing the same maps everywhere.

### ISSUE THREAD

**Issue by Janzert** [HaliteChallenge/Halite-II#261]
Reported by @sveri on the forums at https://forums.halite.io/t/trying-to-replay-a-game-locally/505

The replay says that the engine version was built at commit 32fe1b82b0c388dd06892ceeff005ee5b5bbac8d which should have the new random distribution code. Trying to reproduce the replay locally with an engine built from that commit creates a map of size 384x256 instead of 240x160.

**Comment by sveri** [comment]
Just to be more specific, my halite executable is version: 1.2
I am running on ubuntu 16.04 LTS x86_64.

**Comment by Janzert** [comment]
Ok, your executable is before the recent changes to random number generation and will definitely be different. But even when I locally build an executable that should be the same as the one used in the game it still generates a different map.

**Comment by sveri** [comment]
I tried a few games more and so far this happens for every game, approximately since today 17.00 CET.

**Comment by Snaar** [comment]
@Janzert, I'm a bit confused, why would you get map of size 384x256? Shouldn't you be fixing both seed and map size to be the same? I.e. why would size not be 240x160?

**Comment by Janzert** [comment]
So long as it's not otherwise specified, the seed is supposed to determine the map size along with the rest of the map attributes. I just mentioned it as an easily referencable difference from what the seed produced on the worker.

Oops, and now I see the server is actually having the coordinator specify the map size for some reason instead of leaving it up to the engine and letting it be determined by the seed. And yes once I force the map size to match, the resulting map looks to be the same as the server.

@sveri so it looks like you just need to wait for the latest engine updates to make their way into the downloads and you should be set.

**Comment by sveri** [comment]
@Janzert Hopefully that will do it. Is there an ETA for these? I just saw you released 1.4 of the source code but no builds are available yet. Is that right?

**Comment by Janzert** [comment]
All the releases are done by harikmenon and I haven't heard what his plans are for the next deployment. My best guess though would be sometime today.
