### ISSUE TITLE
Community Contributions

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#264]
@julskast : We need to put together a community contribution list in our docs and update the GitHub readme and other places we call out credit.

**Comment by julskast** [comment]
@harikmenon how do I get the up-to-date list of contributors?

**Comment by harikmenon** [comment]
Lets chat offline about this, a bit of a manual process

**Comment by julskast** [comment]
See PR here: https://github.com/HaliteChallenge/Halite-II/pull/466
