### ISSUE TITLE
Haskell : stack support

### ISSUE THREAD

**Issue by wizzup** [HaliteChallenge/Halite-II#265]
Following discussion on [forum](http://forums.halite.io/t/starter-kit-updates/380/8?u=wizzup)

There is no details description for Haskell. For example:

* What is the compiler version? (`ghc --version`)
* What are libraries available to use? (`ghc-pkg list`)
* What about package management helper? (cabal / stack)

I would love to request for [stack](https://docs.haskellstack.org/en/stable/README/) installation. 

If the official installation method does not applicable, you may adapt instructions from my Halite1 [PR](https://github.com/HaliteChallenge/Halite/pull/282/commits/908e3fbc23aa81aed873570aba0ff53a51a0bdf5)

Additionally, all language should include ecosystem detail in startup bot's README.md

**Comment by lidavidm** [comment]
GHC:
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
$ ghc-pkg list
/usr/lib/ghc/package.conf.d
    Cabal-1.24.2.0
    array-0.5.1.1
    base-4.9.1.0
    binary-0.8.3.0
    bytestring-0.10.8.1
    containers-0.5.7.1
    deepseq-1.4.2.0
    directory-1.3.0.0
    filepath-1.4.1.1
    ghc-8.0.2
    ghc-boot-8.0.2
    ghc-boot-th-8.0.2
    ghc-prim-0.5.0.0
    ghci-8.0.2
    haskeline-0.7.3.0
    hoopl-3.10.2.1
    hpc-0.6.0.3
    integer-gmp-1.0.0.1
    pretty-1.1.3.3
    process-1.4.3.0
    rts-1.0
    template-haskell-2.11.1.0
    terminfo-0.4.0.2
    time-1.6.0.1
    transformers-0.5.2.0
    unix-2.7.2.1
    xhtml-3000.2.1
```

Neither Cabal nor Stack are available, but we can install those.

**Comment by lidavidm** [comment]
I will install these versions, and once we rebuild the worker images and recreate the workers they should be available:

```
$ stack --version
Version 1.1.2 x86_64 hpack-0.14.1
$ cabal --version
cabal-install version 1.24.0.1
compiled using version 1.24.1.0 of the Cabal library
```

Let us know if there is other stuff that would be useful for Haskell. (This is what is available out-of-the-box on Ubuntu 17.04.)

**Comment by wizzup** [comment]
Thank you. Having `stack` should be enough.  I will see if I can modify the existing starter bot to build with stack. Please notify me again when the update worker is online.

You might want to pre-initialized  `stack` by running `stack setup` to shorten the first-time setup time for everyone.

**Comment by lidavidm** [comment]
Got it, thanks for the heads-up.

**Comment by wizzup** [comment]
Also, to support `stack` you might have to choose between
1. detect `stack.yaml` and build with `stack install --local-bin-path .` (the binary will be copy to current directory)
2. let `install.sh/run.sh` do the job as I describe in #283

**Comment by lidavidm** [comment]
@wizzup sorry for the delay, I shouldn't have let this slip under my radar. We have stack and cabal-install now:

```
$ stack --version
Version 1.1.2 x86_64 hpack-0.14.1
$ cabal --version
cabal-install version 1.24.0.1
compiled using version 1.24.1.0 of the Cabal library
```

I'm not sure how well stack will work without being able to override the entire build chain, since the worker will try to run the regular build command afterwards - perhaps adding a separate Haskell target for stack is better?

**Comment by wizzup** [comment]
Thank, I think adding `stack.yaml` as a new target for language detection would be the fastest way to support `stack`

I made a stack version bot from starter bot if you want something to test
[MyBot.zip](https://github.com/HaliteChallenge/Halite-II/files/1501046/MyBot.zip)

**Comment by lidavidm** [comment]
Thanks for the help! #325 implements a target that detects `stack.yaml`.

**Comment by wizzup** [comment]
Thank for your time.

You might want to update [this](https://halite.io/learn-programming-challenge/other-resources/game-servers) and [this](https://halite.io/learn-programming-challenge/downloads-and-starter-kits/customize-bot) pages when the change is online.

**Comment by lidavidm** [comment]
@wizzup It's now live, if you want to give it a spin.

**Comment by wizzup** [comment]
I test uploading my starter bots, both on the site and using hlt_client and have no error but it failed to compile.

The error log on email doesn't help much because it is not complete.

> Downloading lts-9.14 build plan ... Downloaded lts-9.14 build plan. Updating package index Hackage (mirrored at https://github.com/commercialhaskell/all-cabal-hashes.git) ... Fetching package index ... From https://github.com/commercialhaskell/all-cabal-hashes t [tag update] current-hackage -> current-hackage Fetched package index. Populating index cache ... Populated index cache. Did not find .cabal file for hjsonpointer-1.2.0 with Git SHA of 42588498219488475d395388fd77b42a1539098d Right Nothing [1 of 1] Compiling Main ( /tmp/stack13901/Setup.hs, /tmp/stack13901/Setup.o ) Linking /home/bot_compilation/.stack/setup-exe-cache/x86_64-linux/tmp-setup-Simple-Cabal-1.24.2.0-ghc-8.0.2 ... mybot-0.1.0.0: configure Configuring mybot-0.1.0.0... mybot-0.1.0.0: build Preprocessing executable 'MyBot' for mybot-0.1.0.0... [1 of 6] Compiling Hlt.Constants ( src/Hlt/Constants.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Hlt/Constants.o ) [2 of 6] Compiling Hlt.Entity ( src/Hlt/Entity.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Hlt/Entity.o ) [3 of 6] Compiling Hlt.GameMap ( src/Hlt/GameMap.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Hlt/GameMap.o ) [4 of 6] Compiling Hlt.Networking ( src/Hlt/Networking.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Hlt/Networking.o ) [5 of 6] Compiling Hlt.Navigation ( src/Hlt/Navigation.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Hlt/Navigation.o ) [6 of 6] Compiling Main ( src/MyBot.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Main.o ) Linking .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/MyBot/MyBot ... mybot-0.1.0.0: copy/register Installing executable(s) in /home/worker/Halite/apiserver/worker/tmpixei_9a_/.stack-work/install/x86_64-linux/lts-9.14/8.0.2/bin
 
> Once you've fixed your errors, you should submit a new bot!

Could you help trying compile the bot I gave on your side and give me full error log?

**Comment by wizzup** [comment]
This is what log should be like if it success.

    $ stack install --local-bin-path .
    mybot-0.1.0.0: configure (exe)
    Configuring mybot-0.1.0.0...
    mybot-0.1.0.0: build (exe)
    Preprocessing executable 'MyBot' for mybot-0.1.0.0...
    [1 of 6] Compiling Hlt.Constants    ( src/Hlt/Constants.hs, .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Hlt/Constants.o )
    [2 of 6] Compiling Hlt.Entity       ( src/Hlt/Entity.hs, .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Hlt/Entity.o )
    [3 of 6] Compiling Hlt.GameMap      ( src/Hlt/GameMap.hs, .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Hlt/GameMap.o )
    [4 of 6] Compiling Hlt.Networking   ( src/Hlt/Networking.hs, .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Hlt/Networking.o )
    [5 of 6] Compiling Hlt.Navigation   ( src/Hlt/Navigation.hs, .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Hlt/Navigation.o )
    [6 of 6] Compiling Main             ( src/MyBot.hs, .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/MyBot/MyBot-tmp/Main.o )
    Linking .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/MyBot/MyBot ...
    mybot-0.1.0.0: copy/register
    Installing executable(s) in
    /home/wizzup/tmp/mybot/.stack-work/install/x86_64-linux-nix/lts-9.14/8.0.2/bin
    Copying from /home/wizzup/tmp/mybot/.stack-work/install/x86_64-linux-nix/lts-9.14/8.0.2/bin/MyBot to /home/wizzup/tmp/mybot/MyBot

    Copied executables to /home/wizzup/tmp/mybot:
    - MyBot

    WARNING: Installation path /home/wizzup/tmp/mybot not found on the PATH environment variable

**Comment by lidavidm** [comment]
Alright, looks like I didn't filter the output in a very robust way, and so the worker is interpreting the normal output as an error. Once https://github.com/HaliteChallenge/Halite-II/pull/328 lands this should work, sorry for the trouble.

**Comment by lidavidm** [comment]
@wizzup The workers have been uploaded, want to try the Stack bot again?

**Comment by wizzup** [comment]
Thanks, Try it already without any problem.

Apparently, I am the only one who [use](https://halite.io/programming-competition-leaderboard?language=Haskell/Stack) it. 😄
