### ISSUE TITLE
Upgrade rust to 1.21.0

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#274]
https://forums.halite.io/t/update-rust-compiler-version/524

**Comment by lidavidm** [comment]
I'll roll this in while installing Haskell tools/Elixir.

**Comment by Janzert** [comment]
I don't know how rust is effected, but in general there is a need to be careful that upgrading a language doesn't end up breaking current bots. At some point there probably needs to be a version freeze.

**Comment by lidavidm** [comment]
Right. Generally, Rust [avoids breaking backwards compatibility](https://www.rust-lang.org/en-US/faq.html#how-does-rust-language-versioning-work), except in cases of soundness issues/other bugs. We do have Rustup though, so people should be able to select their own versions of Rust if needed.

Hmm, we should probably run this by zxqfl and other Rust players first though.

**Comment by harikmenon** [comment]
Lets not fix it then. I think what we have is sufficient at this time.
