### ISSUE TITLE
Timeouts on server

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#276]
https://halite.io/play/?game_id=2538962&replay_class=1&replay_name=replay-20171111-105838%2B0000--3947291321-312-208-1510397916

other issues: https://forums.halite.io/t/bot-times-out-before-the-game-starts/458/10

**Comment by csheldrick** [comment]
This seems to have stopped happening. Haven’t had a timeout in a few hours

**Comment by harikmenon** [comment]
Interesting, could have been some funkiness in the cloud then. We have seen issues in the past where google cloud storage was unavailable, we would end up with a number of these issues

**Comment by csheldrick** [comment]
How long does it take for a new submission to be the active playing bot? I was thinking my issue may have been the size of my submission. I accidentally included my tensorboard logs, all my test models, etc it was like 49MB zipped. But I cleaned my submission last night and was still timing out until earlier this morning so that may not have been it.

**Comment by csheldrick** [comment]
Of course after I reply: https://halite.io/play?game_id=2559741

**Comment by lidavidm** [comment]
Here's a __*possible*__ cause: as #313 notes, child processes aren't always killed. Over time, a bunch of processes accumulate, and the memory allocated to a bot user gets used up. (Each bot is run in its own cgroup and under its own user.)

```
$ ps aux | grep bot_0
bot_0      547  0.5  0.9 3564284 60676 pts/0   Sl   Nov15  12:49 java MyBot
bot_0     2838  0.5  0.5 3564284 36000 pts/0   Sl   Nov15  12:26 java MyBot
bot_0     5863  0.5  0.9 3564284 59612 pts/0   Sl   Nov15  12:38 java MyBot
bot_0     5926  7.5  0.1 132324 10024 pts/0    Rl   Nov15 204:22 mono MyBot.exe
bot_0     7970  0.5  1.0 3564284 64412 pts/0   Sl   06:14   2:12 java MyBot
bot_0     8522  8.9  0.1 131336  9720 pts/0    Rl   Nov14 329:31 mono MyBot.exe
bot_0     8937  0.5  0.9 3564284 55552 pts/0   Sl   Nov15  17:59 java MyBot
bot_0     9521  0.5  1.2 3564284 78372 pts/0   Sl   Nov15  17:51 java MyBot
bot_0     9757  0.5  1.1 3564284 72948 pts/0   Sl   Nov15  18:26 java MyBot
bot_0    10190  8.9  0.1 131332  9764 pts/0    Rl   Nov15 328:42 mono MyBot.exe
bot_0    12105  7.5  0.1 132324  9820 pts/0    Rl   Nov15 202:25 mono MyBot.exe
bot_0    12168  7.5  0.1 132324  7984 pts/0    Rl   Nov15 202:17 mono MyBot.exe
bot_0    13750  0.7  1.1 3564284 71788 pts/0   Sl   12:19   0:18 java MyBot
bot_0    16519  0.5  1.2 3564284 75460 pts/0   Sl   Nov15  18:12 java MyBot
bot_0    17093  0.5  0.7 3564284 45688 pts/0   Sl   Nov15  18:22 java MyBot
bot_0    17285  9.1  0.1 131332  9512 pts/0    Rl   Nov14 337:39 mono MyBot.exe
bot_0    18348  9.1  0.1 131332 10128 pts/0    Rl   Nov14 336:18 mono MyBot.exe
bot_0    18616  0.5  1.3 3564284 81800 pts/0   Sl   Nov15  15:18 java MyBot
bot_0    19650  7.5  0.1 132324 10020 pts/0    Rl   Nov15 201:09 mono MyBot.exe
bot_0    21152  0.5  0.7 3564284 47932 pts/0   Sl   Nov15  17:22 java MyBot
bot_0    21363  0.5  0.7 3564284 48132 pts/0   Sl   Nov15  18:21 java MyBot
bot_0    21400  9.0  0.1 131332  9924 pts/0    Rl   Nov14 334:25 mono MyBot.exe
bot_0    23670  9.0  0.1 131332  9900 pts/0    Rl   Nov14 333:22 mono MyBot.exe
bot_0    24824  7.2  0.2  38648 12996 pts/0    R    Nov16 123:02 python3.6 MyBot.py
bot_0    28560 11.8  0.9 3497720 61020 pts/0   Sl   Nov14 451:59 java MyBot
```

Using a command to list memory usage by user, we get something like this:

```
$ ps hax -o rss,user | awk '{a[$2]+=$1;}END{for(i in a)print i" "int(a[i]/1024+0.5);}' | sort -rnk2
bot_0 961
bot_1 399
root 302
lightdm 245
bot_3 243
bot_2 223
worker 67
www-data 39
lidavidm 37
systemd-resolve 4
syslog 4
ntp 4
messagebus 4
rtkit 3
avahi 3
daemon 2
nvidia-persistenced 1
```

This is especially bad on GPU workers, which are long-lived. I can easily see a bot going over the memory limit and timing out as a result. If this is true, then we should see player 0 on GPU-enabled games timing out more often.

Curiously enough, it also seems that it tends to be Java/Mono bots that don't terminate properly. There is code in the worker to kill processes after the game ends, but it should be more aggressive about just killing every single bot process. https://github.com/HaliteChallenge/Halite-II/blob/b0dae4b8810bbc7c44fdc3ca68c734d2ae7412b0/apiserver/worker/worker.py#L279-L280

**Comment by AurelC2G** [comment]
Here is a replay where all 4 players seem to time out in the same turn: https://halite.io/play/?game_id=2963994

**Comment by lidavidm** [comment]
We deployed #315 a few days ago - are people still seeing timeouts recently?

**Comment by harikmenon** [comment]
Please reopen this issue if you are still seeing these timeouts.

**Comment by fohristiwhirl** [comment]
Here's a recent game (2 Dec) where everyone times out:

https://halite.io/play/?game_id=3858360&replay_class=1&replay_name=replay-20171202-203745%2B0000--1892558851-384-256-1512246992

**Comment by lidavidm** [comment]
Thanks for finding this. Not sure what's going on here at first glance, unfortunately. I spot-checked some workers and they didn't seem to have a memory leak, and the engine itself doesn't use more than ~500 MB RAM during this game. I'm also guessing that none of the bots involved would have hit the memory limit, either (600 ships isn't _that_ many now right? Plus they timed out together).

**Comment by lidavidm** [comment]
Actually, scratch that, I did the measurement wrong. When I try to take over the replay at the last frame, when the engine tries to send the map state to the bots, I get "Problem writing to pipe". Will investigate further, but I think this will be a new issue.

**Comment by fohristiwhirl** [comment]
The pipe size issue might be relevant in some cases, but presumably not here:

https://halite.io/play/?game_id=3847341&replay_class=0&replay_name=replay-20171202-170749%2B0000--2253008061-240-160-1512234467

**Comment by lidavidm** [comment]
The error logs for that one are quite interesting; all players fail with

```
sudo: unable to resolve host w
```

😕

**Comment by lidavidm** [comment]
Well, I'm guessing that should say something like `sudo: unable to resolve host worker-instances-...` so seems like there might have been a hitch on one of the workers.

**Comment by fohristiwhirl** [comment]
There have been a number of such cases in the past 24 hours. Here's another

https://halite.io/play/?game_id=3888356&replay_class=1&replay_name=replay-20171203-063842%2B0000--3290227288-384-256-1512282749

This happened sometimes last year as well, I dunno if the cause was ever discovered.

**Comment by lidavidm** [comment]
That replay is related to #340.
