### ISSUE TITLE
Submission with install.sh/run.sh should supressed MyBot.ext automatic language detection.

### ISSUE THREAD

**Issue by wizzup** [HaliteChallenge/Halite-II#283]
While waiting for Haskell stack [support](https://github.com/HaliteChallenge/Halite-II/issues/265#issuecomment-343637024), I try to upload modified starter [mybot.zip](https://github.com/HaliteChallenge/Halite-II/files/1464439/mybot.zip) that have `install.sh` and `run.sh` as mention in customization [document](https://halite.io/learn-programming-challenge/downloads-and-starter-kits/customize-bot) but can not submit a zip file that doesn't have `MyBot.ext` in the top-level directory

Error on web.
> ERROR: The zip archive does not contain a root mybot.{ext} file. mybot.{ext} is required to be present in the root of the zip file. 

Error using `halite_client`
> MyBot.* file must be present in the zip's top directory (or cargo.toml in case of Rust).

The basic Haskell `stack` project layout don't have main source file in the top-level directory so it will need custom build script.

Since `install.sh` and `run.sh` was provided, [auto compile](https://github.com/HaliteChallenge/Halite-II/blob/master/apiserver/worker/compiler.py) functionality may need to be skipped for custom one.

For a language detection process of this kind of submit, maybe add a file name `LANGUAGE` would do the trick.

---

Layout of mybot.zip

    .
    ├── install.sh
    ├── run.sh
    └── src
        ├── Hlt
        │   ├── Constants.hs
        │   ├── Entity.hs
        │   ├── GameMap.hs
        │   ├── Navigation.hs
        │   └── Networking.hs
        └── MyBot.hs

Content of `install.sh`

    #!/usr/bin/env bash

    # compile and copy executable to top-lovel directory
    pushd src
    ghc --make MyBot.hs -O -v0 -rtsopts -outputdir dist
    cp MyBot ..
    popd

Content of `run.sh`

    #!/usr/bin/env bash

    # nothing fancy just call the executable directly
    ./MyBot

**Comment by lidavidm** [comment]
Right, you will have to put the contents of `src` in the root of the zip. Though, right now `install.sh` can't really be used to customize the build options like that. 

If Stack is preferable, I think we can add a separate Haskell target that looks for `stack.yaml` (and we can whitelist this in the upload tools so they don't reject it for not having a `MyBot.hs`).

**Comment by Janzert** [comment]
From what I can tell `run.sh` was suppose to be of the format:
* One line starting with a # that defines the language
* One line that contains the command to run the bot

This comes from the functions `get_run_lang` and `get_run_cmd` in [compiler.py](https://github.com/HaliteChallenge/Halite-II/blob/5610d44b669a60d28be403d9c050c8a05d04d795/apiserver/worker/compiler.py#L605-L619).

But it appears that it was never fully implemented, as I can't find any version of `compiler.py` that actually uses them. `compiler.py` will also overwrite any user supplied `run.sh` with the command for whatever language it detects the bot as having.

So I agree that the idea for `run.sh` is that you don't supply a MyBot.{ext} file, but it currently isn't actually implemented.

**Comment by harikmenon** [comment]
Closing this out since it is end of competition, will reconsider for next iteration
