### ISSUE TITLE
Bots failing to compile

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#287]
https://halite.io/user/?user_id=1224

https://github.com/ruyimarone

**Comment by lidavidm** [comment]
Final archive size is too large.

Fix: we will check the upload size and tell the user explicitly if it's too large. Also, we will check the result of the upload instead of ignoring it.

**Comment by harikmenon** [comment]
@lidavidm are we going to send them a compiled failed email as well?

**Comment by lidavidm** [comment]
Yes, this sends them a normal compile failed email.

**Comment by harikmenon** [comment]
Okay sounds good.
