### ISSUE TITLE
Swift bots don't run

### ISSUE THREAD

**Issue by lidavidm** [HaliteChallenge/Halite-II#290]
> Having trouble with the Swift bot I've submitted- it times out immediately. I've tested it locally, and it seems ok. Is it possible that it's not being launched correctly, or there is a permission issue preventing the executable from being launched at all?
> "PlayerName": "./run.sh: line 2: .build/relea"

**Comment by andybest** [comment]
@j-clap @lidavidm Has this gone live yet? My Swift bot still won't run, and I have the same issue

**Comment by lidavidm** [comment]
Ah wait, sorry for the conflicting information - just saw the update on Discord.
