### ISSUE TITLE
hackathon tiers are incorrect

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#292]
The tiers shown on the hackathon leaderboard should pull from the global leaderboard, but instead they're showing up proportional to the hackathon.

E.g this user should be bronze: https://halite.io/user/?user_id=1256

But he's marked as diamond on the hackathon leaderboard: https://halite.io/hackathon-individual?hackathon_id=47&name=two-sigma-new-york-high-school-hackathon
This board is incorrect. All players should be bronze.

We should fix this for all hackathons.

**Comment by toannguyen132** [comment]
@julskast , @harikmenon 

the leaderboard, which is returned from the server, displays the local rank of the users, there is no global rank returned.

<img width="294" alt="hackathon-leaderboard" src="https://user-images.githubusercontent.com/7789414/32796787-ad29368a-c924-11e7-8fd5-c398416ed54b.png">

**Comment by harikmenon** [comment]
Fixed
