### ISSUE TITLE
Fix up download button

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#298]
1. Change color of image to match other buttons on the replay bar (I made it an icon/image instead of text)
2. Fix slider overlapping issues
<img width="949" alt="screen shot 2017-11-14 at 5 25 12 am" src="https://user-images.githubusercontent.com/10966488/32775063-61a58eac-c8fc-11e7-96f4-3f660fd0f741.png">

[](url)

**Comment by harikmenon** [comment]
@toannguyen132 slider overalapping issue is still not fixed

**Comment by toannguyen132** [comment]
@harikmenon I have updated it
