### ISSUE TITLE
Czech republic fails on create/edit pages

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#30]
![image](https://user-images.githubusercontent.com/764613/31910139-8d93d3c8-b80a-11e7-9129-751329f9a264.png)

https://forums.halite.io/t/profile-cannot-set-country/128

**Comment by lidavidm** [comment]
This is actually because the backend expects both a country code and a country subdivision code (error on my part). Fix incoming…

**Comment by lidavidm** [comment]
Actually, I take that back. This seems to behave inconsistently.

**Comment by lidavidm** [comment]
Ah, when updating the user, it fills in their old country subdivision code if present, which obviously isn't correct if they changed their country…

**Comment by harikmenon** [comment]
xerus (username) still seems to have an issue

**Comment by lidavidm** [comment]
@harikmenon The frontend (iso-3166.js) reports there is a district with code CZ-622, but the backend (pycountry) refers to it as CZ-642.

**Comment by lidavidm** [comment]
Nope, the library is just way out of date. Will find a different one, or worst case, export pycountry somehow
