### ISSUE TITLE
Download button only appears for logged in users

### ISSUE THREAD

**Issue by Janzert** [HaliteChallenge/Halite-II#303]
I had a problem and then @erdman mentioned the same thing on discord just minutes later where the download button wasn't appearing on the visualizer. Of course it was caused by neither of us having logged in with the browser in use at the time. Since the browser is getting the replay for the visualizer fine there doesn't appear to be a reason that the download button should need the user logged in either.

**Comment by harikmenon** [comment]
Is there a way for us to get to the download file without going through the user specific API?

**Comment by Janzert** [comment]
Just as a note, even though the replay url includes a user id it doesn't do any authentication or even use it in anyway. So generally on discord the recommended url to download a replay has been `https://api.halite.io/v1/api/user/0/match/<game id>/replay`. The site visualizer actually uses that url as well even if the user is logged in.

**Comment by lidavidm** [comment]
Yes, Janzert is right. You can also use `/replay/class/<int:replay_bucket>/name/<replay_name>` for the case when the game has been deleted from the database, but you still have the replay file name in the URL.

**Comment by Janzert** [comment]
Fix in PR #305, but I didn't link it properly in the other direction. ;)
