### ISSUE TITLE
show hackathon snapshot scores

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#307]
~~We didn't freeze rankings for hackathons, so as players continue to play the board starts to get more and more confusing for example, the Two Sigma hackathon now has players ranked lower with higher scores: https://halite.io/hackathon-individual?hackathon_id=4&name=two-sigma-internal-beta-hackathon~~

~~At the bare minimum, we should hide closed hackathons on the events and hackathons page: https://halite.io/hackathon-and-events~~

So i dug around the DB and we do save scores at the end of the hackathon as a 'snapshot' in the hackathon_snapshot table. Could we please just surface this score on these hackathon pages?

**Comment by harikmenon** [comment]
@lidavidm anything we can do here?

**Comment by lidavidm** [comment]
`/hackathon/<id>/leaderboard` should switch to surfacing data from that table instead of the live table when the hackathon ends.

https://github.com/HaliteChallenge/Halite-II/blob/b01761988d766631960735a7073b2d3f52f55b73/apiserver/apiserver/web/hackathon.py#L236

**Comment by harikmenon** [comment]
Ha I see, so if its closed we pick it up from the other API. got it.

@toannguyen132 : Can you do this?

**Comment by toannguyen132** [comment]
@harikmenon @julskast I don't quite get this. Can you please explain more detail?

**Comment by julskast** [comment]
@toannguyen132 on hackathon pages, pull user score from Halite-II/apiserver/apiserver/web/hackathon.py

Right now it's pulling from the leaderboard API. 

Does that makes sense?

**Comment by toannguyen132** [comment]
On the hackathon pages, it fetches from the URL `/hackathon/<id>/leaderboard`, which leads to `get_hackathon_leaderboard` in the server. Is it correct?

I also have another question: what is the other API in Hari's comment?
`so if its closed we pick it up from the other API. got it.`

**Comment by lidavidm** [comment]
Hmm, I'm not part of any hackathons to check, but if we're already fetching from that endpoint, then it should be showing the correct scores already.

**Comment by julskast** [comment]
@harikmenon any more thoughts here?

@lidavidm the most obvious case of this is Mellendo (Steven Mellendorf). He currently has a point value over 57 on the leaderboard: https://halite.io/user/?user_id=1117

But in his row of the "Hackathon Snapshot" his score was 45.66. That's the score he had when he lost the Halite internal competition.

But now you can see his rating on the TS hackathon page as his *current* score of 57+, which loses the history of the hackathon.
https://halite.io/hackathon-individual?hackathon_id=4&name=two-sigma-internal-beta-hackathon

So we're not showing the correct snapshot scores on the Hackathon pages, we're showing their *current* scores.

**Comment by lidavidm** [comment]
Ah thanks @julskast I'll take a look at what's going on.

**Comment by lidavidm** [comment]
Ah yep, I was selecting from the wrong table when building the query. Sorry about the confusion and how long this took, I should've double-checked the actual query that was being run earlier.

**Comment by lidavidm** [comment]
Once https://github.com/HaliteChallenge/Halite-II/pull/453 is deployed it should be fixed. It should not need a client-side change.

**Comment by julskast** [comment]
Awesome, thanks @lidavidm. Sorry if the original ticket was too vague - I should have included steps to reproduce what I was seeing earlier.
