### ISSUE TITLE
Add API documentation to learn pages

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#31]

**Comment by wizzup** [comment]
Which API? This [one](https://halite.io/learn-programming-challenge/downloads-and-starter-kits/create-new-starter-kit) also called API.

**Comment by harikmenon** [comment]
@wizzup this is for documenting or publishing in the in-code comments in the starter kit, not sure what you mean by it needs formatting.

**Comment by wizzup** [comment]
I mean the single paragraph describe the protocol is hard to read. 

But it is not the problem anymore, I found [good resource](http://forums.halite.io/t/halite-comms-protocol-explained/411) on the forum.
