### ISSUE TITLE
Website certificate not valid for https://2017.halite.io/

### ISSUE THREAD

**Issue by succcubbus** [HaliteChallenge/Halite-II#318]
https://2017.halite.io/ points to the halite website but the load fails due to an insecure connection, likely because the certificate is only valid for "www.halite.io" and "halite.io". The http site redirects without a problem.
Tested in up-to-date versions of Firefox and Chrome.

**Comment by harikmenon** [comment]
@truell20 : can you fix this or if you can send me instructions on how to access the AWS instance, I will move it to 3 year SSL cert.

**Comment by lidavidm** [comment]
Thanks for pointing this out; it's now been fixed after a very long delay 🙈
