### ISSUE TITLE
Installation leads to `multiarray numpy extension module failed`

### ISSUE THREAD

**Issue by halitesubmission** [HaliteChallenge/Halite-II#321]
My halite solution is currently having trouble running (crashes on start).
I added a setup.py file that compiles some C++ and cython code, but do not get a compilation error.
My bot is then run using "MyBot.py" (e.g. autodetected as Python), but apparently fails on run by throwing `ImportError: Importing the multiarray numpy extension module failed.`

Has anyone run into these issues/found a reason why compiling can corrupt the numpy installation?

**Comment by halitesubmission** [comment]
This issue is in fact due to running Python 3.5 instead of 3.6 [possibly vice-versa, not sure].
In any case, if the *right* Python is run (3.6), then this issue goes away.

More pressing:
if install.sh fails during compilation this is not flagged, and no stderr from that process is ever given back to the user. Could someone add this to one of the capabilities [or indicate how to get python install.sh files to be properly detected as working/failing].

My current solution is to:
1. redirecting std-err to a file
2. Use errors as bot name
3. see error logs's bot name to read errors

obviously 2 & 3 are not ideal. Any suggestions?

**Comment by lidavidm** [comment]
Yes, `python3` points to `python3.5` by default, unfortunately (since we're using an older version of Ubuntu). I'll look into getting the output of install.sh included in the log that is sent to you.

**Comment by halitesubmission** [comment]
Thanks. Change seems to add errors from install.sh to the rest of the logs
