### ISSUE TITLE
Error building C++ bot

### ISSUE THREAD

**Issue by 108Shiva** [HaliteChallenge/Halite-II#330]
I had an error building a bot. I then fixed the error and uploaded zip . It still says build error. 
I then loaded a previous zip file that was working. it still says build error. I can now not upload any new bot.
And the current bot does not appear to be running anymoew

**Comment by Snaar** [comment]
I think this is more for someone who can look at the backend logs. @lidavidm?

**Comment by lidavidm** [comment]
@108Shiva Any warnings during build are counted as an error, too, so you'll need to make sure your bot builds without any output from CMake. Your bot is marked as Failed, so you should be able to upload - let me know if you still are not able to, though.

**Comment by 108Shiva** [comment]
Thanks. But i uploaded a previous zip file and it didn't work. it says
build failed. But it had build warnings before as well.

**Comment by 108Shiva** [comment]
its ok now once the build warnings are fixed. But it did work before when i
had build warnings

**Comment by lidavidm** [comment]
Hmm, we did make some changes to how CMake-based bots are built. This change looks like it means your bot might have built directly with gcc before, but now goes through CMake, and the CMake file may have had warnings turned on, whereas we don't: https://github.com/HaliteChallenge/Halite-II/commit/af45177429e68271717398616435f483cc5135cb#diff-2d35e6765fd3268767a985cbf152c50f
