### ISSUE TITLE
Challenges database update

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#331]
I just merged in challenges, not deploying it untill we have the database thingy figured out. @lidavidm - if you are confident that the database schema (including the new leagues table) matches exactly with alembic, you can do go ahead and do the migration. Please take a backup regardless.

But if its risky, i would rather we create the tables by hand for now before i merge and deploy.

**Comment by lidavidm** [comment]
Alright, so to make sure I have the steps down

1. Compare the current schema with `schema.sql`; it should be exactly the same (modulo metadata) minus the `alembic_version` table
2. Make a backup (I will use the [GCloud backup](https://cloud.google.com/sql/docs/mysql/backup-recovery/backing-up#on-demand) for this)
3. Run `alembic stamp head` to actually create that table. In our case this should correspond to `cfaf0d9a46cc, Add leagues table.`
4. Get the new coordinator code (with updated Alembic) and run `alembic upgrade 451d4bb125cb`.

**Comment by harikmenon** [comment]
@Janzert can you double check this. 

@lidavidm I would get the latest schema from msql itself make sure the alembic scripts/schema is currently in sync with it.

**Comment by harikmenon** [comment]
adding @j-clap as well to co-ordinate, hopefully this should address the game id concerns as well.

**Comment by Janzert** [comment]
Since the challenge database updates have already been merged, the current state of schema.sql and the database no longer correspond to the alembic head revision. They should both correspond to revision `cfaf0`. So as long as the live schema corresponds with `schema.sql` the stamp command should be `alembic stamp cfaf0`.

**Comment by lidavidm** [comment]
Alright, I can do the update around noon today then. This doesn't change the game ID field though, but we can use Alembic to do that change later.

**Comment by harikmenon** [comment]
Sounds good.

**Comment by harikmenon** [comment]
@j-clap - sign -off? @lidavidm , please ping me before you start

**Comment by j-clap** [comment]
I approve, especially considering David is doing a backup, so worst case we'll be down momentarily. But from my purview this should be a safe change.

**Comment by lidavidm** [comment]
Ok. Schemas match except for metadata things and the alembic_version table. @harikmenon starting the backup now.

**Comment by lidavidm** [comment]
Migration is complete. Will regenerate the current schema in another PR.
