### ISSUE TITLE
Game feed/Halite TV

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#332]
Opening a issues to track the remaining work for this.  We wanted to build something similar called  Halite TV where users can watch any games they wanted.  In order for this to happen, we need a few things. Once this is done, we can promote this to a top-level Halite TV menu item.

The page is currently live at - https://halite.io/game-feed

* [ ] Rank annotation next to users
* [ ] Search or filters - (Participants to start with )
* [ ] Have the visualizer in the same page, so they can click and watch without having to navigate around.
* [ ] Pause/Resume

**Comment by Janzert** [comment]
I plan to add rank and rating as soon as that information is recorded with a match. Which I plan to finish implementing once the database is updated to store the data along with challenge data.

I'm really not sure that having the visualizer in the same page is going to work well. This is a pretty busy page as it is. Also while you try and watch a single game 100 games are going to scroll by.

I don't understand the last item, update continuously or every x...?

The next thing I did plan to add is a pause/resume button.

**Comment by harikmenon** [comment]
Yep, pause/resume is important. The scenario I think that is important, is users are able to build a playlist of videos to watch to analyze, games. they can search, filter the list to find games that are interesting and then play them one by one. 

The page essentially can become the single place they build their playlist, we can figure out how to show that later (new page or subpage might be fine)

**Comment by julskast** [comment]
I also think it's a little overwealming the way the feed currently updates in real time. As I read the first item in the list, new items appear above it, so I lose my place in the row as my row jumps down. We should think through some kind of reload UI like a facebook or twitter page, where you are alerted that there are new items but they don't automatically reload

**Comment by Janzert** [comment]
For me a major point of it is the real time scroll, it gives a very intuitive feel of how the games are coming in, who's playing fresh resubmits, etc.. The pause button should allow you to stop it and look at individual games if you like.

At the same time the filtering features aren't terribly interesting too me. So maybe the halite tv should be a separate page with the searching/filtering and manual updates.

**Comment by julskast** [comment]
I don't know that it needs to be a separate page, but point taken - maybe we can have a real-time feed as well as a research tool for the two different user stories:
- "As a casual visitor, I want to see how often games are played on Halite"
- "As an existing player, I want to be able to search and filter videos for game analysis"

Plus Hari's existing stories:
- Optional/TBD: "As an existing player doing video analysis, I want to be able to view videos on the same page as the video list to be able to watch a number of videos without needing to hop between pages"
- "I want to be able to find Halite TV on every page of the website - top-level nav"

let me work on a few sketches for the UI and we can see what we like best.

**Comment by harikmenon** [comment]
Closing this out since it is end of competition, will reconsider for next iteration
