### ISSUE TITLE
[scala starterkit] GameMap.nearbyEntitiesByDistance buggy, when two entities have the exact same distance

### ISSUE THREAD

**Issue by FloWi** [HaliteChallenge/Halite-II#339]
Since a Map[Double, Entity] is used as the return type, it fails, when two entities have the exact same distance.
@Snaar suggested on discord to implement it like in the python-starterkit 

> python returns a dict with keys being distance and values are lists of entities

https://github.com/HaliteChallenge/Halite-II/blob/6c58f047c8b80cb272ea5c0f7ee19ba7c3aa464c/airesources/Scala/src/main/scala/hlt/GameMap.scala#L82

**Comment by harikmenon** [comment]
Closing this out since it is end of competition, will reconsider for next iteration
