### ISSUE TITLE
Onboarding issues

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#35]
- [ ] Totally busted for me: https://www.screencast.com/t/TbyHDWbfg
- [ ] Submit needs success & error states

**Comment by julskast** [comment]
@linhle209 I'm really not crazy about having the close tutorial next to the main call to action, it makes it way too prominent. I was thinking about a small "skip tutorial" link in the top right like Duolingo:

![image](https://user-images.githubusercontent.com/764613/31948663-813f1632-b8a5-11e7-9069-e536eaa449bc.png)

From: https://www.appcues.com/blog/the-5-best-user-onboarding-experiences/
Let's not reinvent the wheel here, there are tons of good examples of user onboarding.

**Comment by linhle209** [comment]
Got it. Thanks Julia, we'll update soon within today.
