### ISSUE TITLE
Sometimes bots fail to start with `sudo: failed to resolve host w`

### ISSUE THREAD

**Issue by lidavidm** [HaliteChallenge/Halite-II#350]
I think this is because of GCP changing the hostname.

**Comment by lidavidm** [comment]
After some digging around, I can't find a way to reproduce this. The script that supposedly updates `/etc/hosts` and the hostname doesn't exist on the workers. Trying to manually trigger a DHCP refresh of course causes me to lose my connection to the machine.

**Comment by harikmenon** [comment]
Closing this out untill we can repo this

**Comment by lidavidm** [comment]
- Looking at the database and trying to correlate with the instance group graph, these errors don't seem to correlate with instances being started.
- Trying various things with the hostname/DHCP/DNS resolver don't produce any error like this.
