### ISSUE TITLE
Nemesis section not working

### ISSUE THREAD

**Issue by OliverCole** [HaliteChallenge/Halite-II#351]
I've had several thousand games so far - and I have no nemesis?

https://halite.io/user/?user_id=3117
> Submit your first bot to uncover your nemesis.

**Comment by Janzert** [comment]
Is it showing for you now? It does often take a little bit for the nemesis request to finish and there can be transient failures where it never loads.

**Comment by OliverCole** [comment]
Working now, thanks!
