### ISSUE TITLE
Highest rank ratchet not always working?

### ISSUE THREAD

**Issue by OliverCole** [HaliteChallenge/Halite-II#352]
[My highest rank](https://halite.io/user/?user_id=3117) seems to always match my rank, even when my rank falls. For example, I have seen it say:
Rank: 784
Highest rank: 784

But after a fall to 825, that's now my highest rank, even without resubmitting a bot.

This was working an hour ago, but not currently!

**Comment by Janzert** [comment]
It's rather confusing the way it's worded and implemented. The value shown is the highest of your current rank or the highest rank at which you retired (replaced) a previous version.

**Comment by OliverCole** [comment]
Oh, so literally MAX(current, previous_best_retired).
OK - that is kinda confusing :)

**Comment by harikmenon** [comment]
I added a tooltip to explain this, looks like it wasnt sufficient. I'm pretty close to killing this :)
