### ISSUE TITLE
Holiday planets

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#353]
Hey @lidavidm, we're going to do holiday themed planets for the holiday season - I'm thinking Dec 23 - Jan 1. We got this file from the design team - does it have what you need? https://drive.google.com/drive/folders/195W4r1Dg0ZfI37tK9hdTp1jHoEoaRShb

I think we'd use the one called "winter".

**Comment by lidavidm** [comment]
Hey Julia, I don't have access to this file either - but so long as we have the spritesheet, it should be fine.

**Comment by julskast** [comment]
Try the link now: https://drive.google.com/drive/folders/195W4r1Dg0ZfI37tK9hdTp1jHoEoaRShb?usp=sharing

**Comment by lidavidm** [comment]
Hmm, are there PNG files that come with this?

**Comment by julskast** [comment]
![new_year](https://user-images.githubusercontent.com/764613/33958048-6660365a-e011-11e7-97ad-6484a6c649b8.png)
![winter](https://user-images.githubusercontent.com/764613/33958054-68053352-e011-11e7-8161-d4f0a9f275e6.png)

Got them! (attached) I had a feeling that's what was missing!

**Comment by julskast** [comment]
Wasn’t this supposed to go live today? I went incognito but I still dont see it.

**Comment by lidavidm** [comment]
Janzert pointed out last night that a new version of the website hasn't been deployed in quite a while. I can try and do that tonight.

**Comment by julskast** [comment]
Ok thanks!

**Comment by julskast** [comment]
Just make sure not to publish any of the “challenge a friend” updates

**Comment by lidavidm** [comment]
This should now be live @julskast

**Comment by julskast** [comment]
Confirmed! Looks great!
