### ISSUE TITLE
Find a challenger: Unauthorized

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#357]
*Related to #356 *

- [x] Users who are not signed in should see this dialog overlay on top of the contents of the page they are currently on:

![image](https://user-images.githubusercontent.com/764613/34002593-fd4f6072-e0c0-11e7-8189-a3b009c94dd5.png)

**Comment by julskast** [comment]
@benwong0 updated design with Hoang's updated visuals

**Comment by benwong0** [comment]
@julskast thanks for moving them here.
