### ISSUE TITLE
environment: halite shuld ignore stderr

### ISSUE THREAD

**Issue by wizzup** [HaliteChallenge/Halite-II#366]
From [create-new-starter-kit](https://halite.io/learn-programming-challenge/downloads-and-starter-kits/create-new-starter-kit)

> Bots communicate with the environment via stdin and stdout using series of space separated integers. 

But with given this "do nothing" bot

    import sys
    
    # id
    myid = int(input())
    
    # width, height
    input()
    
    # gamemap
    input()
    
    # response
    print("BotName")
    
    while True:
        # gamemap
        input()
    
        # stderr should be ignore
        print("Ignore me", file=sys.stderr)
    
        #response
        print("")

error was given in log file

    "Message": "ERRORED! Got Exception (if any): ERROR: Bot #0: Received invalid character 'Ignore meI'. (at character 1.)\nInput received from bot:\nIgnore me\n^; Response received (if any): Ignore me",

Can you fix this ? I want to use `stderr` for debugging (in REPL, not when running with `halite`)

**Comment by danielzabotti** [comment]
@wizzup If you're willing to compile the project you can comment out
`dup2(readPipe[1], STDERR_FILENO);` in [Networking.ccp](https://github.com/HaliteChallenge/Halite-II/blob/master/environment/networking/Networking.cpp)

**Comment by wizzup** [comment]
@danielzabotti  Thank, I will try. Is it this [one](https://github.com/HaliteChallenge/Halite-II/blob/master/environment/networking/Networking.cpp#L484) right?

But I wonder why the production code need to read `stderr` from my bot?

**Comment by danielzabotti** [comment]
@wizzup yes!
I dont know why... Its strange. I forgot to mention that the line I pointed out is for *nix builds.

**Comment by harikmenon** [comment]
Closing this out since it is end of competition, will reconsider for next iteration
