### ISSUE TITLE
Challenge API error

### ISSUE THREAD

**Issue by toannguyen132** [HaliteChallenge/Halite-II#369]
I have an issue (500 server error) sending challenge request. The API I used is POST `/v1/api/user/<user_id>/challenge`.

The error message I got:
`Failed to load https://api.halite.io/v1/api/user/1035/challenge: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4000' is therefore not allowed access. The response had HTTP status code 500.`

**Comment by lidavidm** [comment]
Hmm, I made a mistake with the SQL schema, and [used `default` instead of `server_default`](https://github.com/HaliteChallenge/Halite-II/blob/d3ed9a4ad24979277d4a31610c6d9c0c85e42d03/apiserver/alembic/versions/201711081734_49be2190c22d_add_challenges.py#L30).  See #370.

**Comment by julskast** [comment]
@lidavidm With @harikmenon on vacation, can you merge this yourself? Or who has permission to do that?

**Comment by lidavidm** [comment]
I could. I can also deploy, I don't think @harikmenon has changed anything about that process?

**Comment by julskast** [comment]
Not that I know of, but I haven't been super involved

**Comment by lidavidm** [comment]
Alright, I'll merge and deploy it after the cutoff - probably like 11 EST (along with some of the other PRs here).

**Comment by lidavidm** [comment]
Okay @toannguyen132 @julskast the fix for this should now be live.
