### ISSUE TITLE
Fix start/end date/time for college hackathons

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#37]
Can we update start and end times for college hackathons? Should be 9am EST on October 25th through 6pm November 10th.

This is what I see now, looks messy:
![image](https://user-images.githubusercontent.com/764613/31912432-dd59ec42-b811-11e7-9ac5-4340e1692707.png)

Also, can we update the location for Harvard, NYU, and Berkeley to say "Online and On Campus" instead of "Online"?

**Comment by harikmenon** [comment]
@julskast fixed online and on-campus. 

@lidavidm - What the best way to represent date/time in the database so that we get the correct results across timezones on the UI, can you take a look when you get a chance and fix it up?

**Comment by lidavidm** [comment]
@harikmenon dates/times are stored in the database in UTC. We should make sure we're properly converting between UTC and local time in the frontend, and make sure the server isn't converting things accidentally.

**Comment by lidavidm** [comment]
Yeah, the date and time are stored 'correctly' but in GMT. The frontend needs to convert to GMT when it sends and convert from GMT when it displays.
```
{
  "description": "...", 
  "end_date": "Fri, 10 Nov 2017 23:59:00 GMT", 
  "hackathon_id": 19, 
  "location": "Online", 
  "num_participants": 0, 
  "organization_id": 17031, 
  "organization_name": "Brown University", 
  "start_date": "Mon, 23 Oct 2017 09:00:00 GMT", 
  "status": "open", 
  "thumbnail": null, 
  "title": "Brown University"
}
```

**Comment by lidavidm** [comment]
@harikmenon , how are you creating hackathons at the moment?

**Comment by harikmenon** [comment]
dont hate me, directly uploaded a file with all the hackthons in csv

**Comment by lidavidm** [comment]
No worries, wanted to make sure. When I get out of classes,I can fix the
times in the database directly (I assume they were meant to be EST?) and
then in the future make sure to upload them in UTC.

**Comment by lidavidm** [comment]
Actually @julskast or @harikmenon do you have the list of correct times? The database has 10/23 9 AM UTC as the start date for the Brown hackathon, but it should be 10/25 9 AM EST as per the original comment?

**Comment by harikmenon** [comment]
All Hackathons except for Two Sigma, Two Sigma High School, Cornell Tech, Harvard and Berkeyly should be 10/25 9:00 EST to November 15th 11:59 PM

**Comment by julskast** [comment]
Yes please make them all 10/25 - hackathon start was delayed until tomorrow!

**Comment by harikmenon** [comment]
I will fix the others up later

**Comment by lidavidm** [comment]
Ah, the weird minute is because moment.js uses MM for month and mm for minute (even though it uses HH for hour -.-)

**Comment by lidavidm** [comment]
In any case, I've fixed the dates/times for the hackathons (except that list) in the database. @harikmenon I will add a PR to correct the moment.js date formatting stuff

**Comment by julskast** [comment]
@harikmenon  the end date of the hackathons was meant to be the 10th, but ellen's fine with the 15th. which is what you & david set it to. But now we need to change the HTML in all the page descriptions bc they don't match either the start or end dates. can you help fix that?
