### ISSUE TITLE
Workers priority or dedicated for gold+ bots

### ISSUE THREAD

**Issue by reCurs3** [HaliteChallenge/Halite-II#379]
Since the new player surge last Friday, it now takes at least an order of magnitude longer to reach 400 games. The number of sub-400 games submissions has gone from less than 100 to over 1200 in the past few days. This threshold is very important for high level bots, in order to get meaningful results over changes as fast as possible. As it currently stands, with the short amount of time left in the challenge, top bots are losing many precious days to improve.

It does not sound feasible (and very expensive) to increase the workers to reach the level we had before for every submission, where I think it took approximately 2-4 hours for 400 games. My suggestion would be to either have a pool of workers dedicated exclusively (or equivalently modify the algorithm to give more priority) at playing games for gold bots and above, determined by the seed player, in order to get quick feedback like we used to.

I think this or an equivalent is critical to keep iterating on high level bots.

Thanks!

Original forum thread: https://forums.halite.io/t/suggestion-locked-workers-for-gold-bots/848

**Comment by scottlegrand** [comment]
This is going to have a profound effect on latecomers to this competition IMO (~1/3 of the participants now).  They're going to need significantly better offline evaluation tools than those of us who joined earlier (and I'm a bit of late bloomer myself here at joining on 12/3).  I'm super happy I'm in the gold tier already, but I want a good shot at hitting platinum/diamond and I want the newbies to have the same shot too and I really wonder if I could have made the progress I've made at the current rate of convergence.

**Comment by reCurs3** [comment]
I have serious doubts you need anywhere near the same level of convergence to reach gold league. Improvements are easy to spot and measure before that point.

**Comment by scottlegrand** [comment]
Heh, I would 100% agree all the way to silver.  Not so sure about gold though.  I was borderline gold waiting on hitting 500+ games and then the Holiday Zerg Rush happened (and lowered the gold criteria) and I agree with you going forward assuming the 1500+ newbies don't hit gold anytime soon, but I am now intentionally waiting on submitting a new client to get better statistics on my current submission and like you stated previously, that's slowing down innovation, and probably much worse for you and @FakePsyho, no?

**Comment by shummie** [comment]
I hope that the current situation in which the wave has started dying down doesn't kill this discussion. I guarantee that once we're in the last few days of the competition we'll be running into the same issues. This happened in Halite 1 where the last weekend of the competition saw a TON of resubmissions. (of course, the huge meta shift at the time didn't help). I reckon we'll see something similar and i think given the points Recurse pointed out above that this would be useful to mitigate the impact we'll see in the last week.

**Comment by harikmenon** [comment]
Closing this out since it is end of competition, will reconsider for next iteration
