### ISSUE TITLE
Google analytics fixes post-launch

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#38]
**Switch category & action for subscribe events:**

- [ ] Subscribe is the category. click-to-subscribe = subscribe-error + subscribe-success, which are the actions. This way I can see unique click-to-subscribe (the number of individual ppl trying to subscribe) vs. the errors.
![image](https://user-images.githubusercontent.com/764613/31912517-284ba510-b812-11e7-8ab4-11ece50db2bf.png)

**Other priority issues**
- [ ] Can we track the share flow now? click-to-share and click-share-copy click-share-facebook, click-share-linkedin, click-share-twitter
- [ ] Didn’t get analytics event for hackathon error (when I entered garbage instead of a code)
- [ ] I also didn’t get analytics event for hackathon error when I tried to sign up for harvard without validating
- [ ] Didn’t get analytics event when I entered garbage email (julia.kastner)

**Onboarding Flow**

- [ ] We should have analytics events for clicking next for each page of the onboarding flow:	
Category: onboarding
Action: clicked-next
Label: page-{number of page, 1-3}

- [ ] Also click to cancel:
Category: onboarding
Action: clicked-cancel
Label: page-{number of page, 1-3}

- [ ] Maybe also track downloads?
Category: onboarding
Action: clicked-download
Label: {language user selected}

**Low priority:**
- [ ] I clicked on all TS links on homepage but only got one event
- [ ] I clicked on forum on top nav & homepage but only got one event
- [ ] No events from clicks on cornell & google on homepage
- [ ] I got click-to-sign-up even though I was actually signing in. Can we differentiate?
- [ ] When I submited a replay I got “select-replay-file-another” - why another? It was my first replay with this user?
- [ ] Can we track events on video speed toggle on visualizer?

**Comment by harikmenon** [comment]
Given we are at the end of the competition, closing this out. Will consider for Halite III
