### ISSUE TITLE
A single upload bumped bot version by 3

### ISSUE THREAD

**Issue by wizzup** [HaliteChallenge/Halite-II#383]
I am not sure where the bug is between `hlt` or the website

![2017-12-27-090318_685x209_scrot](https://user-images.githubusercontent.com/342500/34368270-14576a70-eae5-11e7-8f2c-89860849642e.png)

My bot was upload using `hlt` tool (the version number is off by -1 is known [bug](https://github.com/HaliteChallenge/Halite-II/issues/326#issuecomment-347441638), it should report `43`)

![2017-12-27-090602_597x49_scrot](https://user-images.githubusercontent.com/342500/34368288-37db09de-eae5-11e7-8709-2c6218b88f40.png)

**Comment by Janzert** [comment]
This is pretty certainly a result of #382

**Comment by Janzert** [comment]
This should now be fixed along with #382. Let us know if you still see it happening.
