### ISSUE TITLE
Challenge a Friend Bugs

### ISSUE THREAD

**Issue by benwong0** [HaliteChallenge/Halite-II#387]
- [x] Can't remove a user after adding it. It'll continue to show error about selecting a friend.
To reproduce, challenge someone to open the dialog, then click on "Add more opponents" and add someone. Then try to remove that user. The search box shows up again.<img width="647" alt="screen shot 2017-12-27 at 8 20 52 pm" src="https://user-images.githubusercontent.com/5994802/34391210-96447df2-eb44-11e7-8458-d06fdd5e41cd.png">

- [x] Challenge a friend dialog never resets when stay on the same page. It just stuck at the last state it was in. This makes it impossible to get out of the bug above unless a user reload the page.
To reproduce, challenge someone in the leaderboard, then try to challenge someone else. You should see the dialog stuck at success state like below.<img width="705" alt="screen shot 2017-12-27 at 8 35 10 pm" src="https://user-images.githubusercontent.com/5994802/34391376-79ada8fc-eb45-11e7-9b47-2146a14450c5.png">

**Comment by julskast** [comment]
I've got some too:

- [ ] If user is not logged in, it should say 'sign in' and link to github flow.
![image](https://user-images.githubusercontent.com/764613/34391619-cadef270-eb14-11e7-9da9-f4beb4d7ac99.png)

- [ ] move challenges column to the left to after tier column
![image](https://user-images.githubusercontent.com/764613/34391686-5c67a426-eb15-11e7-8cba-b7a8cb01def8.png)

- [ ] Error messages should disappear once fixed and user should be able to resubmit a form. E.g. if user tries to submit with two players, they should see the error, but then if they add a third player or delete a player the error state should go away. (similar to Ben's bugs above)

- [ ] When a user clicks " " it should add two more user fields 
![image](https://user-images.githubusercontent.com/764613/34391762-c2695cd8-eb15-11e7-8546-970a71cac871.png)

- [ ] A user should not be able to add any more fields after two additional fields have been added.

- [ ] A user should not be able to add the same player to a challenge twice
![image](https://user-images.githubusercontent.com/764613/34391855-5ebbbe1e-eb16-11e7-92d9-f6b267a4b290.png)

to be continued...

**Comment by benwong0** [comment]
@julskast for 
> results should be their own widget in the user profile - see design. https://invis.io/NTCQDM0EC#/269347949_01_User_Profile_Analyze

What is the Games column mean and where does it link to? We have a num_games data passing back from the server, looks like that's what this column is. But there is no game ID, so can't link to a specific game. Also, sounds like the column is about number of games played? Linking to a specific game doesn't seem to make sense either.

**Comment by benwong0** [comment]
@julskast @harikmenon for
> Video results from challenges should not show up on the game videos feed on the games & logs tab on the user profile - this widget should only be videos that are not part of a challenge.

Is there a way to filter out the challenges in the API? Right now, we have two APIs, one for all games (`/user/{id}/match?{query}`), and one for just challenges (`/user/{id}/challenge`). The all games one is what we have in that tab right now, which seems to include the challenge games.  However, there is no flag in the data to identify the challenges. Is there any way to filter out the challenges from the all games list?

**Comment by Janzert** [comment]
You can identify challenge games in the `/user/{id}/match` api results by looking at the `challenge_id` field, see #390 for an example of use. There I just changed the background color so they were marked in the game list though.

**Comment by julskast** [comment]
@benwong0 regarding the challenge widget, that was supposed to link to Halite TV which hasn't been built yet, so let's leave it as is without links for now.

Other feedback on latest iteration:

- [ ] If user submits with only two players, the error message should be “Please select one or three players to challenge”. Note that if user submits when no players selected, this copy is correct: “Please select at least one player to challenge”.

- [ ] If user clicks “add” and two more fields appear but the user has cleared out both of the two fields, they should be able to still submit just one player:
![image](https://user-images.githubusercontent.com/764613/34419537-6d15daaa-ebd2-11e7-9cc9-0235b7cb2dee.png)

- [ ] For challenges widget, the most recent challenge should be at the top
- [ ] For challenges widget, the order of participants should be the same as the videos feed widget, with the current user first.
- [ ] for the challenges widget, if no games have been played yet, all players should be in first place (or no numbers should appear)
- [ ] For the challenges widget, the trophy should only appear for a winner once the challenge has been completed:
![image](https://user-images.githubusercontent.com/764613/34419619-da86768a-ebd2-11e7-8f2f-f73451568140.png)

**Comment by toannguyen132** [comment]
@Janzert So I need to fetch all games and filter non-challenge games in the client? Can I fetch and receive non-challenge games only from the server? I have to display most 10 recent games. If I have to filter non-challenge games, I have to fetch more than 10 games (number of requested games is undecidable).

**Comment by Janzert** [comment]
With the addition of #388 you can filter in the query now. To get all non-challenge games use something like `filter=challenge_id,=,null` in your query.

**Comment by julskast** [comment]
Closing this issue, opening up one more little one for the tool tip. Great work! 

Time to move onto Halite TV
