### ISSUE TITLE
Offline visualizer bugs from forum

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#39]
https://forums.halite.io/t/standalone-visualiser-installation-errors/140

**Comment by harikmenon** [comment]
Do we need to update the instructions here?

**Comment by julskast** [comment]
Yes, that sounds like the right fix to me @harikmenon cc @j-clap

**Comment by lidavidm** [comment]
The bug is because the package-lock has the old path. I was using Yarn,
which has its own lockfile, so I didn't notice. It should be a quick fix to
update the lockfile but it'll be a while before I have access to a computer.

**Comment by julskast** [comment]
No hurry @lidavidm - thanks for taking a look!

**Comment by lidavidm** [comment]
Fixing the build problem itself was OK, but some changes on the website have broken the visualizer, looking into it

**Comment by lidavidm** [comment]
@harikmenon I'm not sure about the error with Jekyll/`x64_mingw`; it might be safe just to remove it, but I haven't tested. (It's intended for Windows users.)
