### ISSUE TITLE
Turkish characters

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#394]
Kırıkkale is shown as K?r?kkale

- [ ] Can we make sure we support Turkish characters as an org name on the leaderboard, user profile, etc.?

**Comment by toannguyen132** [comment]
@julskast the content font is “helvetica neue” and users may not have it. I currently use web-font (client will download font) to display it correctly. Should I just declare ‘helvetica neue’ and if the users don’t have it, they will see default font instead? I think this is the best way to fix this issue.

**Comment by julskast** [comment]
@toannguyen132 sounds good to me! thanks!

**Comment by toannguyen132** [comment]
@julskast can you please provide me a screenshot of it. Where did you get that issue?

**Comment by julskast** [comment]
<img width="1191" alt="screen shot 2018-01-03 at 4 43 09 pm" src="https://user-images.githubusercontent.com/764613/34541164-3a2cc536-f0a5-11e7-8d29-4ae952b007b4.png">

If you filter the leaderboard by "Turkey" the first name has ? in it where the special characters should be.

https://halite.io/programming-competition-leaderboard?country=TUR

**Comment by toannguyen132** [comment]
@julskast Those characters are originally returned from the server. I think this is not the font issue.

<img width="356" alt="returned characters" src="https://user-images.githubusercontent.com/7789414/34553807-583fe024-f0de-11e7-9078-573fe179e1d2.png">

**Comment by julskast** [comment]
![image](https://user-images.githubusercontent.com/764613/34570120-e003cb42-f138-11e7-9ad4-291f3045a154.png)

Perhaps it's both front end and backend? Here's the user's profile https://halite.io/user/?user_id=6169

@lidavidm any thoughts here? would be nice to support these turkish characters if we can, but we obviously can't support all characters in every language...

**Comment by lidavidm** [comment]
It's a configuration issue in the backend. I'll let Hari know for the next redeployment.

**Comment by harikmenon** [comment]
Closing issue since competition is ended
