### ISSUE TITLE
Tool tip for challenges

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#397]
It should read:
A challenge will run for 30 games. Challenge games will not affect your score and will never make up more than 10% of total games running while the competition is live. You can initiate up to three challenges per day.

**Comment by julskast** [comment]
@lidavidm this was my copy proposal (with some recent edits) but feel free to ignore if this is already updated.

**Comment by lidavidm** [comment]
Got it, I've updated the PR.
