### ISSUE TITLE
Halite TV page

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#398]
- [x] Top level of the nav
- [x] Video viewer - same controls as visualizer but no stats, just plays the first game of the feed when page loads
- [x] Expand icon takes user to that game as a visualizer page in a new tab
- [x] Video feed: most recent videos. Prototype is here: https://halite.io/game-feed
- [x] User should be able to filter games using the same filters as the leaderboard - filters by the players in the game. If any player meets the filter criteria, the game is eligible.
- [x] If user filters list of videos, the feed at the top of the page should filter too and URL should change to reflect query (so we can share filters)
- [ ] List of videos at the bottom is same as game video widget on the user profile except demarcates which videos are challenges
- [x] Responsive: feed should fall below video area, hide expand icon, filters same as leaderboard, and the list of videos should match the user profile video widget

![image](https://user-images.githubusercontent.com/764613/34445583-b4b39fca-eca2-11e7-9505-9d35dccb80a9.png)

**Comment by julskast** [comment]
@benwong0  I've made an issue for Halite TV. Let me know if this is clear.

**Comment by toannguyen132** [comment]
@julskast are the filter factors the same with those of leaderboard? as I saw in the API, it accepts different filter parameters:
`game_id`, `time_played`, `views_total`, `turns_total`, `turns_total`, `planets_destroyed`, `ships_produced`, `ships_destroyed`, `challenge_id`

**Comment by benwong0** [comment]
@harikmenon @julskast we have one last item left:
> List of videos at the bottom is same as game video widget on the user profile except demarcates which videos are challenges

Can you take a look at @toannguyen132's question above. Thanks!

**Comment by benwong0** [comment]
Also for 
> Video feed: most recent videos. Prototype is here: https://halite.io/game-feed

Should the feed automatically update by itself every few seconds like in the prototype.

**Comment by julskast** [comment]
Hi @benwong0 excited for this page!

Yes, the video feed should update like the prototype to start. If we get feedback that it's too difficult to follow maybe we'll slow it down later.

The challenge icon doesn't have anywhere to link to, it's just to signify which ones are challenges.

And @toannguyen132 yes, ideally we'd be able to filter the videos by the characteristics of the users in the games, not by the features of the games. So you should be able to filter by say country, and any game that has at least one player from that country should appear.  Does that make sense?

**Comment by benwong0** [comment]
@julskast From what I understand, Toan is using (`/apiserver/apiserver/web/match.py`) which has parameters for `game_id, time_played, views_total, turns_total, turns_total, planets_destroyed, ships_produced, ships_destroyed, challenge_id`.

It doesn't seem to match the filter dropdowns in the design. The filters in design looks exactly like the ones from Leaderboard, which requires a different sets of parameters. @toannguyen132 does that sound accurate?

**Comment by julskast** [comment]
@harikmenon @lidavidm any thoughts here? The goal would be to be able to filter videos by at least username if not by other characteristics of users in a game.

**Comment by lidavidm** [comment]
As we noted on Discord, you can't filter by any characteristic of the participants, except you can view matches containing a particular user by using a different endpoint (`/v1/api/user/<id>/match`).

**Comment by toannguyen132** [comment]
@lidavidm @julskast so at least we can fetch all matches by one username via the endpoint `/v1/api/user/<id>/match`. Other characteristics cannot be filtered because they are not supported.

**Comment by julskast** [comment]
Got it. So let’s add the filter to see all games from a single user. I think that’s still a valuable feature.

**Comment by julskast** [comment]
(And let’s remove all other filters)

**Comment by toannguyen132** [comment]
@lidavidm I got this error when request to the endpoint `/v1/api/user/<id>/match`. Do you know how can I get risk of this error?
<img width="690" alt="screenshot 2018-01-10 23 35 52" src="https://user-images.githubusercontent.com/7789414/34813484-05e47d90-f65f-11e7-8625-1fc486b4d0a9.png">

**Comment by lidavidm** [comment]
@toannguyen132 Looks like the trailing slash trips it up. `api.halite.io/v1/api/user/4355/match` should work.

**Comment by harikmenon** [comment]
Closing this out since it is end of competition, will reconsider for next iteration
