### ISSUE TITLE
Typo on Unit Reference Page?

### ISSUE THREAD

**Issue by kamn** [HaliteChallenge/Halite-II#4]
https://halite.io/learn-programming-challenge/basic-game-rules/units
https://github.com/HaliteChallenge/Halite-II/blob/2ff792f77a3f485cfaa1253ad72488dac7aef30c/website/learn-programming-challenge/basic-game-rules/units.md

See the Planet Properties specifically  `Explosion Radius` and `Production` have the same description. Could be wrong but I don't think they should be the same.

**Comment by harikmenon** [comment]
Thanks for catching that. It was wrong. Just fixed it.
