### ISSUE TITLE
Explorable org map

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#400]
https://docs.google.com/spreadsheets/d/1NIIuzYs7Z4a6w48ufJ4yYnm38Ih3C1_JpASLe4U_qC0/edit#gid=1714023779

Use org addresses to plot on a map like https://www.easymapmaker.com/map/fd022c563e96bfcbab281ad7548919db - would be explorable geography.

Use cases:
- Embed in a forum post
- Link from social media and email

**Comment by harikmenon** [comment]
Closing issue since competition is ended
