### ISSUE TITLE
Paused challenges

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#402]
Sometimes players on the leaderboard can't play in a challenge. E.g. opponents with currently disabled bots (due to compilation) won't have a bot to play.

- [ ] Let's add a state to the analysis widget for 'paused' if at least one player in the challenge does not have a bot. 

E.g.
![image](https://user-images.githubusercontent.com/764613/34448195-310a8906-ecb9-11e7-9e38-9e1e2170d571.png)

**Comment by toannguyen132** [comment]
@harikmenon how can I get the pause status in the response of server? All I can see in the `finished ` key of the response is bool value (true or false).

**Comment by julskast** [comment]
@lidavidm any suggestions here?

**Comment by lidavidm** [comment]
We don't explicitly return it in the API, but you can check the compilation status of the participants' bots (or whether they even have uploaded a bot yet).

```
$ curl https://api.halite.io/v1/api/user/1000/bot/0
{
  "bot_id": 0, 
  "compilation_status": "Successful", 
  "games_played": 562, 
  "language": "Python", 
  "rank": 942, 
  "score": 26.6559, 
  "version_number": 14
}
```

**Comment by julskast** [comment]
Thanks @lidavidm ! @toannguyen132 let us know if this makes sense. cc @benwong0

**Comment by toannguyen132** [comment]
@lidavidm so I need to fetch all the participants' information in each challenge in the list to get the compilation status in order to display?

**Comment by lidavidm** [comment]
@toannguyen132 Yes, all the bots of all the participants, if the challenge is not completed. If that's too many requests, then let's just add it to the API.

**Comment by toannguyen132** [comment]
@lidavidm I have updated the paused status. But I do not know any user those don't have any bot or failed compilation to test. I tried to fail my bot by uploading the wrong bot but it still shows my bot status 'successful'. I think it uses my previous version.
Do you have any example user like that?

**Comment by lidavidm** [comment]
@toannguyen132 I just updated my bot to fail (user 1000), does that help?
