### ISSUE TITLE
Challenges transactional emails

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#414]
I've created three transactional emails in Sendgrid:

- [ ] When a challenge is initiated, every player should receive an email: 451e76ab-010e-458c-9cf9-f213c40934c4
- [ ] When a challenge is paused, every player should receive an email: ea89d508-38e1-465d-882c-3869b6c8cdda
- [ ] When a challenge is finished, every player should receive an email: fc874474-c83b-4cd5-b3c1-599c0014ce3e

Note: All emails should be in the subscription group Challenge Notifications number 11851

- [ ] And this subscription group should be added to the list of groups a user can alway manage from their user profile (for all templates)

**Comment by julskast** [comment]
Hey @harikmenon I've set everything up for transactional emails for challenges. Before we release this, though, we should warn top players so they can unsubscribe from these notifications.

**Comment by julskast** [comment]
Already got feedback from discord
From top players: "I still think it would be preferable to make it challenger-only, if I wanted to do challenges and be notified of it, my only option would be to allow the other spam as well."
"Maybe make two categories: challenges you initiated, and challenges others initiated"

Does it make sense to have two sets of transactional emails with separate unsubscribe groups? Seems like a bunch of added complexity for a low priority feature

**Comment by harikmenon** [comment]
Closing this out since it is end of competition, will reconsider for next iteration
