### ISSUE TITLE
Auto refresh game feed on profile page

### ISSUE THREAD

**Issue by swapagarwal** [HaliteChallenge/Halite-II#417]

**Comment by julskast** [comment]
Hi @swapagarwal could you give a bit more detail? You mean a live feed that updates itself like the new Halite TV feed (top right corner): https://halite.io/halite-tv

**Comment by swapagarwal** [comment]
Yes.

**Comment by harikmenon** [comment]
Closing this out since it is end of competition, will reconsider for next iteration
