### ISSUE TITLE
Prepping for post-competition

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#422]
We've had a request for more time from a lot of the players - they want to keep playing after the competition ends. We don't want to extend the competition.

Requirements would be:
- Rankings shouldn't be impacted
- Games shouldn't play if not part of a challenge
- Users should be able to keep submitting bots
- User profile should continue to update but only for challenges widget and video stream challenge videos

UI:
- User submits a bot as normal, goes through error detection
- If bot submits successfully, should pop up the challenge modal asking user to choose competitors
- Only when user successfully submits a challenge does their bot start playing games
- If user submits a bot but does not submit a valid challenge, nothing should happen - no score change, no bots played

API:
- Make sure that if users submit a bot via API they get a message that their bot won't count and prompt them to submit a challenge?

@lidavidm @harikmenon  Sound good to you? Doable?

**Comment by lidavidm** [comment]
This shouldn't be a problem. The main change is recognizing that the competition is closed, then only issuing challenge games.

**Comment by Janzert** [comment]
You'll also want to at least stop sigma from being reset when submitting a new bot. I can't think of anything else offhand that will touch the leaderboard in a significant<sup>1</sup> way offhand but a review of the code would probably be good.

<sup>1</sup> New users will get added to the leaderboard with a 0 rating, but that's probably not a real problem.

**Comment by julskast** [comment]
I agree @Janzert - I think that's fine. It was happening like that with Halite I when I joined the team -  when I registered I was added to the bottom of the leaderboard (that leaderboard showed all registered users).

**Comment by julskast** [comment]
Per conversation with @harikmenon we think we're going to skip the challenge-only period unless something changes. We're not sure we have capacity to support features and infrastructure after the game ends.
