### ISSUE TITLE
Prepping for finals

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#423]
Engineering requirements for finals

**On Jan 22nd at 11:59pm EST:**
- close bot submissions
- Turn off matchmaking to reset all bots
- Turn matchmaking back on to play games to update scores
(for all of these, see much more detailed specs from Janzert below)
- Homepage top banner changes
- Submissions blocked on 'play' page
-- If user arrives at play page, should see a screen that submissions have closed. But can still do replays. See mockup in comments below.

**On Jan 29th at 9:00:00am EST:**
- stop playing games
- stop updating rankings / sigma / mu
- update homepage banner
- Other changes:
1. Homepage 'get started' and 'SUBMIT A BOT' buttons should be hidden
2. Top nav 'submit a bot' button should be hidden (but not the sign up / sign in button)
3. Add banner to top of 'learn' pages to say that competition has ended?
4. Update About page.
5. Make sure status page properly shows what's online vs. offline
6. QA all user profile zero states to ensure 'submit a bot' CTA is gone. And CTA to do a challenge, join a hackathon, etc.
7. Disable challenge modal whenever challenges initiated, replace with a message
8. Registration flow: hide fields for organization. User can register but without specifying level or org.
9. Onboarding flow
~~

**Comment by julskast** [comment]
@harikmenon @lidavidm @j-clap  Let me know if this sounds good and if I'm missing anything. Happy to chat through it too.

**Comment by Janzert** [comment]
With the current architecture submissions need to be closed during the whole finals. It will also require some changes to reopen them just for challenges afterward but it shouldn't be too extensive.

The schedule set on https://halite.io/learn-programming-challenge/contest-rules/ has said 6 full days of games with some ambiguity when the games would stop on the 7th day.
> At midnight on January 22nd, we will close submissions and let the final bots play each other for the last week of January. We will announce final winners on January 29th based on the final scores at that point in time and will freeze scores.

3 days might be doable but will probably be tight.

There are a few more steps needed to start the finals, some comments in PR #355 listed a few things. I need to dig out the checklist from last year to make sure there aren't other steps I'm forgetting as well.

**Comment by julskast** [comment]
@Janzert Thanks for pointing out those rules (which I wrote but just forgot!) Better to follow the original schedule. I knew I didn't want to announce anything on a weekend, so I guess I chose to do Monday instead of Friday.

I'll adjust the above schedule

**Comment by Janzert** [comment]
Here's a detailed checklist for switching the servers over to running the finals. I can certainly encode the raw sql queries into scripts if desired

* Close submissions
   * First set `COMPETITION_OPEN = False` in `config.py`
   * Then restart all coordinators and public api servers
* Wait for all last minute submissions to finish compiling.
   * The query `select * from bot where compile_status in ('Uploaded', 'InProgress');` will return any bots still compiling.
* Stop all coordinators.
* Not required but now would be a good time to run a database backup.
    * This will be the final state of the database for the open competition.
* Get the id of the last game played and record it as the last open game.
   * Query `select max(id) from game;`
   * Set `LAST_OPEN_GAME` to that id in `config.py`
* Enable finals pairing
   * Set `COMPETITION_FINALS_PAIRING = True` in `config.py`
* Run rating reset
   * from `halite/apiserver` directory `python -m apiserver.scripts.rating_reset`
   * that will do a test run and rollback the transaction
   * to commit the reset add `--execute` option to the end.
* Verify rating reset was successful
   * The leaderboard should show everyone at 0 rating and with `mu=25` and `sigma=8.333`
   * The bot history of each user should show their most recently retired bot as having just been retired with the rating and rank information being their finish in the open competition.
* Restart all public api servers
   * So they pick up the `config.py` changes.
* Start coordinators back up.
* Congratulations the finals are now running.

**Comment by julskast** [comment]
1. Nav banners. 

![image](https://user-images.githubusercontent.com/764613/35058005-a03a0e9e-fb84-11e7-85e5-09f8395ff6b0.png)
Bot submissions close on January 22nd, 11:59 PM ET. Check out the plan for finals.

![image](https://user-images.githubusercontent.com/764613/35057859-3d2a5c46-fb84-11e7-964f-0337fadd4571.png)
Submissions for the 2017-2018 are closed. Check out the finals in progress.

![image](https://user-images.githubusercontent.com/764613/35057947-73927728-fb84-11e7-847f-795895d5d8cb.png)
The 2017-2018 season has ended. Check out this year's winners!

**Comment by julskast** [comment]
Play page update:
![image](https://user-images.githubusercontent.com/764613/35077528-e5814e08-fbcb-11e7-8c8a-70e748b572db.png)

```<div data-v-8c5003f2="" class="panel-body text-center"><h2 data-v-8c5003f2="">SUBMISSIONS HAVE CLOSED</h2> <p data-v-8c5003f2="" style="text-align: center;">The 2017-2018 season of Halite has ended. But you can still<a data-v-8c5003f2="" href="https://api.halite.io/v1/login/github"> sign up </a>to join our newsletter to be the first to know about future competitions.</p></div>```

**Comment by julskast** [comment]
Send challenge modal:
```<div data-v-48c46ce0="" class="send-challenge-form"><img data-v-48c46ce0="" src="/assets/images/icon-group.svg" class="ico"> <h2 data-v-48c46ce0="" class="heading">CHALLENGE OTHER PLAYERS</h2> <p data-v-48c46ce0="">The 2017-2018 season of Halite has ended. You can no longer challenge a player through our website. But you can always play Halite locally - read <a href="/learn-programming-challenge/halite-cli-and-tools/">our documentation</a> to learn more.</p> </div>```

![image](https://user-images.githubusercontent.com/764613/35077755-b70aed30-fbcc-11e7-9fd3-cde61e14ce63.png)

**Comment by julskast** [comment]
Account page with hidden fields:
![image](https://user-images.githubusercontent.com/764613/35077823-0e8ee19c-fbcd-11e7-8214-e09ce263571a.png)
