### ISSUE TITLE
nav responsiveness needs update

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#425]
At ~1150px width, forums start to overlap with button:

![image](https://user-images.githubusercontent.com/764613/34960760-46af6cc8-fa0a-11e7-8b87-7f6cf75c5c55.png)

Nav needs new break point now that there are more top-level links.

**Comment by toannguyen132** [comment]
@julskast what should the nav be? turn into a dropdown list like in mobile?
