### ISSUE TITLE
Error message when user tries to submit 4th challenge in a day

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#436]
![image](https://user-images.githubusercontent.com/764613/34960633-ac5a0a2a-fa09-11e7-9019-b832982e6a24.png)

If user has already submitted 3 challenges and tries to submit a 4th, show this error message. Copy is:
Sorry, you can only initiate 3 challenges per day. Please wait until tomorrow to initiate a challenge.

**Comment by julskast** [comment]
@lidavidm lmk if you have time to do this real quick, if not maybe Ben's team can.

**Comment by harikmenon** [comment]
Closing this out since it is end of competition, will reconsider for next iteration
