### ISSUE TITLE
4 player challenges can still play 2 player games

### ISSUE THREAD

**Issue by Janzert** [HaliteChallenge/Halite-II#438]
See challenge 1174 for an example.
http://api.halite.io/v1/api/challenge/1174
http://api.halite.io/v1/api/challenge/1174/match

Most of the games are played only between the issuer and tscommander-ml.

In this case I believe it is because tsadmiral and tscaptain have is_gpu_enabled turned on. So they only play if the challenge happens to be selected to play on a gpu enabled server.

I believe it's also the case that if one of the challenged bots had a failed upload or was otherwise disabled the remaining two challenged bots would continue playing 2 player games against the issuer.

**Comment by julskast** [comment]
@lidavidm I thought we paused the whole challenge if any player's bot was disabled?

**Comment by lidavidm** [comment]
If the initiator's bot is disabled, yes, otherwise it will keep trying to play games. I guess we should probably make sure all bots are at least eligible to participate.

**Comment by julskast** [comment]
yes @lidavidm I think that makes more sense

**Comment by harikmenon** [comment]
Closing issue since competition is ended
