### ISSUE TITLE
Set up Google cloud for team project prototype

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#441]
- [ ] Fix error message that cmd line - Google Cloud - not able to run server - IP address & port says not connecting.
- [ ] Make sure we can see code on Google Cloud working correctly

**Comment by julskast** [comment]
@j-clap - Helene is stuck on this ticket.

**Comment by helenem80** [comment]
yes, please help me.....

**Comment by julskast** [comment]
Moving to other board
