### ISSUE TITLE
UI Changes for finals - Jan 22nd when submissions close

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#448]
- [x]  Homepage banner update
![image](https://user-images.githubusercontent.com/764613/35057859-3d2a5c46-fb84-11e7-964f-0337fadd4571.png)
```<div class="notification font-headline">Submissions for the 2017-2018 are closed. <a href="/finals-status" style="text-transform:underline !important; color:#25242f; font-weight:bold;">Check out the finals in progress.</a></div>```

- [x]  Homepage  'SUBMIT A BOT' button should be hidden (when user is logged in)
![image](https://user-images.githubusercontent.com/764613/35169066-1ea1274a-fd29-11e7-98c7-a7f98e065f01.png)

- [x] Play page updated to hide submissions
```<div data-v-2c45658c="" id="bot-upload-container" class="upload-container"><div data-v-2c45658c="" class="upload-desc text-center"><h2 data-v-2c45658c="">Submissions have closed</h2> <p data-v-2c45658c="">The 2017-2018 season of Halite has ended. But you can still<a data-v-8c5003f2="" href="https://api.halite.io/v1/login/github"> sign up </a>to join our newsletter to be the first to know about future competitions.</p> </div>  </div>```
![image](https://user-images.githubusercontent.com/764613/35169370-519af382-fd2a-11e7-98a1-b772caa85620.png)

- [x]  Top nav 'submit a bot' button should be hidden (but not the sign up / sign in button)
![image](https://user-images.githubusercontent.com/764613/35168956-c4068f82-fd28-11e7-8097-1e2a05581b7e.png)

- [x]  all user profile zero states to ensure 'submit a bot' CTA is gone. 
![image](https://user-images.githubusercontent.com/764613/35170924-d7efc4d0-fd2f-11e7-9880-a1a9c8255eea.png)
- Game feed zero state
- Nemesis zero state
- Rating zero state
- History zero state

- [ ] Edit page - hide affiliation edit
![image](https://user-images.githubusercontent.com/764613/35170999-2f38ddc6-fd30-11e7-817e-d3e23b71d7b7.png)

- [x] Disable challenge modal whenever challenges initiated, replace with a message
```<div data-v-48c46ce0="" class="send-challenge-form"><img data-v-48c46ce0="" src="/assets/images/icon-group.svg" class="ico"> <h2 data-v-48c46ce0="" class="heading">CHALLENGE OTHER PLAYERS</h2> <p data-v-48c46ce0="">The 2017-2018 season of Halite has ended. You can no longer challenge a player through our website. But you can always play Halite locally - read <a href="/learn-programming-challenge/halite-cli-and-tools/">our documentation</a> to learn more.</p> </div>```
![image](https://user-images.githubusercontent.com/764613/35077755-b70aed30-fbcc-11e7-9fd3-cde61e14ce63.png)

- [ ]  Registration flow: hide fields for organization. User can register but without specifying level or org.
![image](https://user-images.githubusercontent.com/764613/35077823-0e8ee19c-fbcd-11e7-8214-e09ce263571a.png)

- [x]  Hide Onboarding flow: when user creates an account and clicks submit, should take user to /learn-programming-challenge page without onboarding overlay

**Comment by harikmenon** [comment]
I'm taking care of this.
