### ISSUE TITLE
Py 3 timeout game.update_map()

### ISSUE THREAD

**Issue by harchuk** [HaliteChallenge/Halite-II#45]
After several games noticed that on the python 3 built-in functions in hlt (game.update_map ()) is sometimes executed too long which leads to a timeout! Argghhhhhh!

**Comment by Zlogdan** [comment]
i know what you feel bro
the waiting time reaches 2 sec

**Comment by harikmenon** [comment]
@j-clap, any thoughts on this?

**Comment by harikmenon** [comment]
This is a duplicate of https://github.com/HaliteChallenge/Halite-II/issues/20
