### ISSUE TITLE
Halite TV Pause/Unpause Button

### ISSUE THREAD

**Issue by FrankWhoee** [HaliteChallenge/Halite-II#459]
The following image is being used for resuming the replay:
![image](https://user-images.githubusercontent.com/34866813/35316669-c860004c-0087-11e8-9a50-e88fdf4bf59c.png)

The following image is being used to pause the replay:
![image](https://user-images.githubusercontent.com/34866813/35316706-ea6e2952-0087-11e8-9034-3f9d7a5ae5c0.png)

This is the opposite for other replays, such as the ones that I access through my profile. Is it meant to be this way? It feels very counter-intuitive. This is my first time opening an issue, so hopefully I did it right :smile:

**Comment by harikmenon** [comment]
This is fixed, will only deploy after the finals are done :).
