### ISSUE TITLE
hamburger menu won't open

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#465]
One last bug of the Halite project! We can't get the hamburger menu to open.

Steps to reproduce:
- click on navigation hamburger menu
- Navigation flashes open then closed

Could you help us fix this last thing?

**Comment by toannguyen132** [comment]
@julskast I have just created a PR containing the fix. Please review

**Comment by julskast** [comment]
@harikmenon are we gtg on this?
