### ISSUE TITLE
Windows 32 bit prebuilt kit

### ISSUE THREAD

**Issue by Snaar** [HaliteChallenge/Halite-II#49]
32bit windows is still very common in lots of world. Should probably provide prebuilt one.

**Comment by harikmenon** [comment]
https://github.com/HaliteChallenge/Halite-II/issues/90

**Comment by harikmenon** [comment]
closing this issue since this is completed

**Comment by Snaar** [comment]
Actually, this was more about adding another kit with "Windows 32 bit" to the https://halite.io/learn-programming-challenge/downloads-and-starter-kits/ matrix. We can build 32 bit executable on existing 64 bit machine - msvs supports cross-compilation like that fine.

**Comment by Snaar** [comment]
@harikmenon what does the package script actually run to make the 64 bit version? Is it just make.bat?

I'll prepare bat file for you that will build 32 bit version using same toolchain that you run and then you can take over from there

**Comment by harikmenon** [comment]
@Snaar we build this in appveyour, and we just call make there

**Comment by Snaar** [comment]
@harikmenon there are currently three projects in appveyor all called Halite-II. Two of them are for the public github and one is for pre-release private github. The only difference between the two public ones seems to be the "Skip branches without appveyor.yml" checkbox.

Do you mind if I remove the two extra projects and leave just one of the public ones? It's a bit confusing with three of them there.

**Comment by harikmenon** [comment]
@Snaar yep that is fine. Please keep the one that had the latest build on it.

**Comment by Snaar** [comment]
@harikmenon there is "Halite-II 32 bit" project in appveyor now that builds 32 bit halite executable. I'm not sure if we actually need to provide the kit for now, but the project and the executable artifact is there if anyone needs them.

I wasn't sure which of the duplicate projects to remove, so I've renamed one of them to "Halite-II-deletion-candidate". Can you check if that is the right one?

**Comment by Snaar** [comment]
Also for completeness - there are two appveyor config files now in github - one is the original appveyor.yml that builds 64 bit executable and new one appveyor32.yml that builds 32 bit executable.

**Comment by harikmenon** [comment]
@Snaar : should we just provide a link in the downloads page for users to download the 32 bit version then?

**Comment by Snaar** [comment]
If it's not too hard to do, sure.

**Comment by harikmenon** [comment]
Given we are at the end of the competition, closing this out. Will consider for Halite III
