### ISSUE TITLE
Game Stats HTTPS/HTTP Mixing Error

### ISSUE THREAD

**Issue by truell20** [HaliteChallenge/Halite-II#6]
https://halite.io/game-player-stats won't load in my Chrome browser. It seems that its loading http resources.

Console output:
<img width="578" alt="error" src="https://user-images.githubusercontent.com/4297743/31874275-5f516828-b796-11e7-9855-bee23ea29209.PNG">

**Comment by harikmenon** [comment]
Yep known issue. Will fix it today.

**Comment by harikmenon** [comment]
This should be fixed in the next deployment. Directly linking to the stats dashboard
