### ISSUE TITLE
Support bot submissions with single directory in zip file root

### ISSUE THREAD

**Issue by Snaar** [HaliteChallenge/Halite-II#62]
Seems like a common thing is people submitting zip files with single directory inside where all the bot code is. Maybe it's worth supporting that instead of asking them to repackage it?

**Comment by Snaar** [comment]
Inspired by https://forums.halite.io/t/the-zip-archive-does-not-contain-a-root-mybot-ext-file/170 and chat comments.

**Comment by Janzert** [comment]
When implementing, probably best to support it with the extra __MACOSX directory automatically added by macOS as well.
