### ISSUE TITLE
Color-blindness: find color of neutral planets in visualizer

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#82]
Hari, can you help the design team find the current styling of neutral planets in the visualizer?
Then we'll test a couple options with filters on to find a better option.

**Comment by lidavidm** [comment]
Neutral planets just use use a tint color of #b7b7b7: https://github.com/HaliteChallenge/Halite-II/blob/f40c3ec572d14f8c7e429a253e75d55d8ddb3a29/libhaliteviz/src/assets.js#L10

**Comment by harikmenon** [comment]
the color is here, closing the issue
