### ISSUE TITLE
How to submit a new Starter Kit?

### ISSUE THREAD

**Issue by wimrijnders** [HaliteChallenge/Halite-II#83]
Hi there,

I've got a Ruby Starter Kit lined up and would like to submit it.

They usual way that I do this is to clone the repo in question and submit a branch from there. However, the Halite-II repo is so huge it's taking hours just to clone. And after that, I'll have to push it again to my own github account.

Is there a better way of submitting a PR? Would like to hear from you. In the meantime, I'll let the cloning chug along.

**Comment by harikmenon** [comment]
@wimrijnders. Thank you for your contribution! we just got another for a ruby bot PR. Not sure how different they are, do you want to collaborate on that instead?

**Comment by wimrijnders** [comment]
:cry: That is definitely my worst case scenario. Was pushing forward to be the first and got beaten while I was pushing to my repo. I'll think I'll go sulk for a while.

**Comment by harikmenon** [comment]
Oh sorry about that, we still value your contribution, you can always make changes once we get the intial version in. Any other language you want to do it in? I will open a ticket and assign it to you and block that one for you :)

**Comment by wimrijnders** [comment]
The other PR looks OK to me. I'll leave it as is.

No, just ruby. Couldn't care about the rest. Not that I think that it's suitable for the job, in fact the opposite. I just want to show that it's possible.

I'll just concentrate on my bot now, based on my own starter kit.
