### ISSUE TITLE
Feature request: Display production info on the game replay screen

### ISSUE THREAD

**Issue by jenheilemann** [HaliteChallenge/Halite-II#85]
Since overall production is the main tie-breaker, could there be some information about current/total production on the game replay page?

If it's there and I'm not seeing it, just call me a derp please.

**Comment by harikmenon** [comment]
Did you look at the post game dashboard it has a cumulative total ships graph :) Since you contributed the starter bot, no name calling for you!

**Comment by jenheilemann** [comment]
Ah, so that's essentially the same as production? I guess I was just confused about the terminology. Thanks :D
