### ISSUE TITLE
Weird filter leaderboard UI

### ISSUE THREAD

**Issue by julskast** [HaliteChallenge/Halite-II#86]
![image](https://user-images.githubusercontent.com/764613/32024674-6c8f96ba-b9ab-11e7-88b2-d45aa60bdb7d.png)

![image](https://user-images.githubusercontent.com/764613/32024687-73c5c1ac-b9ab-11e7-9d31-500b7e2d5d7a.png)

Weird that the arrow moves. I'd expect it to stay in the top right corner and for tags to fill around it.

**Comment by julskast** [comment]
@harikmenon worth fixing? It kinda looks broken.

**Comment by harikmenon** [comment]
I would say wont fix at this time :(
