### ISSUE TITLE
Add Key Bindings for Gameplay Speed

### ISSUE THREAD

**Issue by willisjtc** [HaliteChallenge/Halite-II#9]
halite 1 allowed you to press 1,2,3,4,5 to change the game speed. It would be super nice to set that up this time as well

**Comment by jenheilemann** [comment]
As another option, having a dropdown of some sort to quickly switch between speeds would be awesome.

Just a thought too, I'd bet a lot of money that most people are using only a few of the speeds between 0.5 and 10 - I'd bet on 0.5 and 10 definitely, and probably 2-5 more fuzzily. I'd be fine if 7-9 are gone completely.

**Comment by toannguyen132** [comment]
added the keyboard event so you can change the speed by pressing 1,2,3,4,5 on the keyboard

**Comment by harikmenon** [comment]
@toannguyen132 why are we not adding support for 6,7,8,9,10? Can you add that as well?

**Comment by toannguyen132** [comment]
@harikmenon okay, but there is no key 10, do you want me to map the key 0 to 10?

**Comment by harikmenon** [comment]
This is completed
