### ISSUE TITLE
Incorrect ranking

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#93]
https://halite.io/play/?game_id=1908412&replay_class=0&replay_name=replay-20171026-094429%2B0000--71771732-240-160-1509011061

Rabbi - Today at 8:24 AM
This was a clear cut victory for me but it says the other guy won.. any ideas?  https://halite.io/play/?game_id=1908412&replay_class=0&replay_name=replay-20171026-094429%2B0000--71771732-240-160-1509011061
Halite AI Challenge
Halite AI Programming Challenge Videos
Watch replays your favorite games

fohristiwhirl - Today at 8:25 AM
If you're sjonesy it's saying you won
harikmenon - Today at 8:28 AM
thats weird
https://github.com/HaliteChallenge/Halite-II/issues/93
GitHub
Incorrect ranking · Issue #93 · HaliteChallenge/Halite-II
https://halite.io/play/?game_id=1908412&replay_class=0&replay_name=replay-20171026-094429%2B0000--71771732-240-160-1509011061 Sj* won this right, why is piotr bing awarded the win?

opened an issue
could be just a UI issue though
Rabbi - Today at 8:29 AM
I am sjonesy, weird.. https://i.imgur.com/rvsX2K6.png

Thanks guys
fohristiwhirl - Today at 8:31 AM
did you post the right link?
wait it is
never mind
Rabbi - Today at 8:32 AM
1908412, yeah
fohristiwhirl - Today at 8:32 AM
sec

I see this

Sj* won this right, why is piotr bing awarded the win?

**Comment by fohristiwhirl** [comment]
I think Sj was in fact awarded the win. It's in his history as a win (as least for me).

**Comment by harikmenon** [comment]
this is probably just a ui bug

**Comment by harikmenon** [comment]
@benwong0 please fix this asap, I'm pretty sure a recent UI change broke this.

**Comment by harikmenon** [comment]
I had to revert this to fix it https://github.com/HaliteChallenge/Halite-II/commit/c2e0d5586b9f2b450437aad688ead060ecb509b3

**Comment by harikmenon** [comment]
this is fixed
